### PR TITLE
feat: support tilt since 0.22.15

### PR DESCRIPTION
**Pull request by sgtoj**
## Description
#1009 - Minor update to remove the out dated suffix of `_ALPHA` for `tilt` when installing on ARM.

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
```
make test
```

If updating or adding a new CLI to `arkade get`, run:

```
go build && ./hack/test-tool.sh tilt
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by sgtoj** [comment]
## Output for `./hack/test-tool.sh`

```
+ ./arkade get tilt --arch arm64 --os darwin --quiet
+ file /Users/brian/.arkade/bin/tilt
/Users/brian/.arkade/bin/tilt: Mach-O 64-bit executable x86_64
+ rm /Users/brian/.arkade/bin/tilt
+ echo

+ ./arkade get tilt --arch x86_64 --os darwin --quiet
+ file /Users/brian/.arkade/bin/tilt
/Users/brian/.arkade/bin/tilt: Mach-O 64-bit executable x86_64
+ rm /Users/brian/.arkade/bin/tilt
+ echo

+ ./arkade get tilt --arch x86_64 --os linux --quiet
+ file /Users/brian/.arkade/bin/tilt
/Users/brian/.arkade/bin/tilt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=00faf54f3aa1a26f966d027921512ef8a6e71156, for GNU/Linux 3.2.0, stripped
+ rm /Users/brian/.arkade/bin/tilt
+ echo

+ ./arkade get tilt --arch aarch64 --os linux --quiet
+ file /Users/brian/.arkade/bin/tilt
/Users/brian/.arkade/bin/tilt: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, Go BuildID=5-F9CBcRhjlrErxbHipA/208amWVCzRf9QYm9Xw5O/D_cs7mDqfYrHF-p2N_J5/9ZDXoxYzZd-JEmN6TM68, BuildID[sha1]=804dc4ac4489922e015ce1cf4dff61a0c18c8ec5, stripped
+ rm /Users/brian/.arkade/bin/tilt
+ echo

+ ./arkade get tilt --arch x86_64 --os mingw --quiet
+ file /Users/brian/.arkade/bin/tilt.exe
/Users/brian/.arkade/bin/tilt.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /Users/brian/.arkade/bin/tilt.exe
+ echo
```

**Review by Shikachuu — APPROVED** [review]
Seems fine and necessary, thanks for the PR!

**Comment by sgtoj** [comment]
What are the next steps for this PR?

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
