### PR TITLE
Example to showcase some simplifications.

### PR DESCRIPTION
**Pull request by aidun**
## Description

This should showcase some simplifications and show how to reduce code duplication for common helm3 apps.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by aidun** [comment]
😅 I will push a few more changes tomorrow. Pre and post actions should be no problem if we rely on Interfaces at this point.

**Comment by alexellis** [comment]
This appears to remove manual steps for plain YAML artifacts such as CRDs, do you plan to do anything else?

**Comment by aidun** [comment]
I was working on the pre and post actions @Waterdrips mentioned. I struggled while prototyping because I have the do more than I thought.

The pre and post actions are really different from app to app, so you have to generalize it through an interface. To test the interface I need to make for example kubectl apply as Task type which implements the interface.

I don’t know if I am running in the right direction. Do you have any thoughts on this?

**Comment by alexellis** [comment]
Perhaps a proposal issue would be better for this type of discussion? Have you seen #21 yet? Feel free to move over there to continue the discussion.

@Waterdrips has already had a go at implementing some of this for the Loki app.

**Pull request closed without merging**
