### PR TITLE
Add croc cli

### LINKED ISSUE #850: Add Support for croc
## Expected Behaviour

Add croc CLI to the arkade get
https://github.com/schollz/croc

## Current Behaviour
Error: tool croc not found

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

Total Downloads: 115,077

### PR DESCRIPTION
**Pull request by tuxtof**
## Description

Add croc CLI to the arkade get
https://github.com/schollz/croc

## Motivation and Context

- [X] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
Closes #850 

## How Has This Been Tested?

```
./hack/test-tool.sh croc                                                                                                                                                                                         11s
+ go build
+ ./arkade get croc --arch arm64 --os darwin --quiet
+ file /Users/cris/.arkade/bin/croc
/Users/cris/.arkade/bin/croc: Mach-O 64-bit executable arm64
+ rm /Users/cris/.arkade/bin/croc
+ ./arkade get croc --arch x86_64 --os darwin --quiet
+ file /Users/cris/.arkade/bin/croc
/Users/cris/.arkade/bin/croc: Mach-O 64-bit executable x86_64
+ rm /Users/cris/.arkade/bin/croc
+ ./arkade get croc --arch x86_64 --os linux --quiet
+ file /Users/cris/.arkade/bin/croc
/Users/cris/.arkade/bin/croc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=oZO-uWt8H6Yd449Bsv9M/nAC8jOjGt4Z45eZRbRvF/ttNW7BkBwxZXZPDV1i10/8ro6CkMk86-p8TPTxTJO, stripped
+ rm /Users/cris/.arkade/bin/croc
+ ./arkade get croc --arch arm64 --os linux --quiet
+ file /Users/cris/.arkade/bin/croc
/Users/cris/.arkade/bin/croc: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=m7haxEc6AGnqavkDE_Zz/SsOKaZXirV-3mYcWECFu/VmPfzBF3l6gcOzFmi9QD/GBCgPSW8nQxeljCft-YU, stripped
+ rm /Users/cris/.arkade/bin/croc
+ ./arkade get croc --arch x86_64 --os ming --quiet
+ file /Users/cris/.arkade/bin/croc
/Users/cris/.arkade/bin/croc: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=m7haxEc6AGnqavkDE_Zz/SsOKaZXirV-3mYcWECFu/VmPfzBF3l6gcOzFmi9QD/GBCgPSW8nQxeljCft-YU, stripped
+ rm /Users/cris/.arkade/bin/croc
```

```
 make e2e
...
=== RUN   Test_CheckTools/Download_of_croc
=== PAUSE Test_CheckTools/Download_of_croc
=== CONT  Test_CheckTools/Download_of_croc
    --- PASS: Test_CheckTools/Download_of_croc (5.32s)
...
PASS
coverage: 55.0% of statements
ok  	github.com/alexellis/arkade/pkg/get	(cached)	coverage: 55.0% of statements
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]
@alexellis you may want to take a look. LGTM. 👍🏻

**Comment by Jasstkn** [comment]
@alexellis hi. are there any blockers to review and merge this?

**Comment by alexellis** [comment]
Hey @Jasstkn 

Thanks for reviewing it. I haven't been able to look at this request yet due to work demands.

The best way to accelerate things or get things onto my radar would be on the [weekly Office Hours call for OpenFaaS](https://docs.openfaas.com/community/#weekly-office-hours), where we also talk about arkade.

That said, when GitHub sponsors submit requests, I'll try to prioritise their needs first, too.

Alex

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
FYI @tuxtof https://github.com/alexellis/arkade/releases/tag/0.9.0

**Pull request merged**
