### PR TITLE
Download binaries to separate temp directory

### LINKED ISSUE #911: Failures in multi user envronments
## Expected Behaviour

A different user has run arkade to install yq, now this user wants to do it, and it fails because the temp download file is not permissioned correctly

CleanShot 2023-05-21 at 08 16 29@2x

### PR DESCRIPTION
**Pull request by alexellis**
## Description

Fixes #911 where files were downloaded to the same directory with permissions that prevented another user from running arkade get.

The changes remove the concept of stash which I don't think was used or useful and replaces it with a default path for the current behaviour or --path to match the way that system installers work today.

## Motivation and Context

Fixes #911 

## How Has This Been Tested?

Tested with a single download and multiple downloads via arkade get with and without a custom path. The files were executable by the owner as expected.

Default:

```
alex@bq:~/go/src/github.com/alexellis/arkade$ go run . get k9s 
Downloading: k9s
2023/05/23 11:46:10 Looking up version for k9s
2023/05/23 11:46:10 Found: v0.27.4
Downloading: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
17.80 MiB / 17.80 MiB [----------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-592201071/k9s_Linux_amd64.tar.gz written.
2023/05/23 11:46:10 Looking up version for k9s
2023/05/23 11:46:11 Found: v0.27.4
2023/05/23 11:46:11 Extracted: /tmp/arkade-592201071/k9s
2023/05/23 11:46:11 Copying /tmp/arkade-592201071/k9s to /home/alex/.arkade/bin/k9s

Wrote: /home/alex/.arkade/bin/k9s (60.56MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/alex/.arkade/bin/k9s

# Or install with:
sudo mv /home/alex/.arkade/bin/k9s /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
alex@bq:~/go/src/github.com/alexellis/arkade$ ls ~/.arkade/bin/
k9s

```

Custom directory:

```
alex@bq:~/go/src/github.com/alexellis/arkade$ go run . get k9s --path /tmp/binaries/
Downloading: k9s
2023/05/23 11:45:41 Looking up version for k9s
2023/05/23 11:45:41 Found: v0.27.4
Downloading: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
17.80 MiB / 17.80 MiB [----------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-3900916076/k9s_Linux_amd64.tar.gz written.
2023/05/23 11:45:41 Looking up version for k9s
2023/05/23 11:45:41 Found: v0.27.4
2023/05/23 11:45:42 Extracted: /tmp/arkade-3900916076/k9s
2023/05/23 11:45:42 Copying /tmp/arkade-3900916076/k9s to /tmp/binaries/k9s

Wrote: /tmp/binaries/k9s (60.56MB)

Run the following to copy to install the tool:

sudo install -m 755 /tmp/binaries/k9s /usr/local/bin/k9s

🐳 arkade needs your support: https://github.com/sponsors/alexellis
alex@bq:~/go/src/github.com/alexellis/arkade$ ls /tmp/binaries/
k9s
```

Multiple binaries to a custom path:

```
alex@bq:~/go/src/github.com/alexellis/arkade$ go run . get kubectx kubens k9s --path /tmp/binaries/
Downloading: kubectx
2023/05/23 11:46:32 Looking up version for kubectx
2023/05/23 11:46:33 Found: v0.9.4
Downloading: https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubectx
5.96 KiB / 5.96 KiB [------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-2721537142/kubectx written.
2023/05/23 11:46:33 Looking up version for kubectx
2023/05/23 11:46:33 Found: v0.9.4
2023/05/23 11:46:33 Copying /tmp/arkade-2721537142/kubectx to /tmp/binaries/kubectx

Wrote: /tmp/binaries/kubectx (6.108kB)

Downloading: kubens
2023/05/23 11:46:33 Looking up version for kubens
2023/05/23 11:46:34 Found: v0.9.4
Downloading: https://github.com/ahmetb/kubectx/releases/download/v0.9.4/kubens
5.42 KiB / 5.42 KiB [------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-3493732447/kubens written.
2023/05/23 11:46:34 Looking up version for kubens
2023/05/23 11:46:34 Found: v0.9.4
2023/05/23 11:46:34 Copying /tmp/arkade-3493732447/kubens to /tmp/binaries/kubens

Wrote: /tmp/binaries/kubens (5.555kB)

Downloading: k9s
2023/05/23 11:46:34 Looking up version for k9s
2023/05/23 11:46:34 Found: v0.27.4
Downloading: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
17.80 MiB / 17.80 MiB [----------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-2472131393/k9s_Linux_amd64.tar.gz written.
2023/05/23 11:46:35 Looking up version for k9s
2023/05/23 11:46:35 Found: v0.27.4
2023/05/23 11:46:35 Extracted: /tmp/arkade-2472131393/k9s
2023/05/23 11:46:35 Copying /tmp/arkade-2472131393/k9s to /tmp/binaries/k9s

Wrote: /tmp/binaries/k9s (60.56MB)

Run the following to copy to install the tool:

sudo install -m 755 /tmp/binaries/kubectx /usr/local/bin/kubectx
sudo install -m 755 /tmp/binaries/kubens /usr/local/bin/kubens
sudo install -m 755 /tmp/binaries/k9s /usr/local/bin/k9s

🐳 arkade needs your support: https://github.com/sponsors/alexellis
alex@bq:~/go/src/github.com/alexellis/arkade$ ls /tmp/binaries/
k9s  kubectx  kubens
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

`--stash` is removed, but I don't think it was being used.

I also changed `--output/-o` to `--format` for clarity

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

### CODE REVIEW

**Comment by alexellis** [comment]
@NikhilSharmaWe @nitishkumar71 do you want to both take a look at these changes and give them a try?

**Comment by NikhilSharmaWe** [comment]
I think these are reasonable changes based on the issue. Now we are extracting files in uniquely named folder `/tmp/arkade-*` each time and providing the read, write and execute permission too.

**Comment by alexellis** [comment]
Perhaps you could try out a few scenarios?

**Comment by roderik** [comment]
FYI, i hit the issue with the github actions, (@alexellis arm-01 and amd-01) with 10x native github client each in their own linux user, 2 or more concurrent CI runs

**Pull request merged**
