### PR TITLE
Add kubectl-slice.

### PR DESCRIPTION
**Pull request by patrickdappollonio**
Adding `kubectl-slice` (or `slice` if you use it without `kubectl`). Per request from #884 

## Description
Adds the download for `kubectl-slice`.

## Motivation and Context
It was requested in #884 
- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Unit test for the download function

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Adding a new tool

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hey @patrickdappollonio please read the note from Derek 

We'll also need you to run `./hack/test-tool.sh slice` or `./hack/test-tool.sh kubectl-slice` (whichever you went for)

Thanks,

Alex

**Comment by alexellis** [comment]
It's because you've used a fake email address. If you fix that it will remove the label. No reply addresses are not allowed by policy as they don't make sense for what the DCO is about.

**Comment by alexellis** [comment]
No worries, sorry we couldn't accept your PR. The DCO is invalid with an anonymous email that is not contactable.

**Comment by patrickdappollonio** [comment]
No problem! Thanks a lot.

**Pull request closed without merging**
