### PR TITLE
Add atuin

### PR DESCRIPTION
**Pull request by lbrealdev**
## Description

PR created to add atuin sync bash history tool, requested in the issue https://github.com/alexellis/arkade/issues/903

## Motivation and Context

- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

make e2e
```
=== RUN   Test_DownloadAtuin
--- PASS: Test_DownloadAtuin (0.00s)
=== RUN   Test_CheckTools/Download_of_atuin
=== PAUSE Test_CheckTools/Download_of_atuin
=== CONT  Test_CheckTools/Download_of_atuin
--- PASS: Test_CheckTools/Download_of_atuin (0.88s)
```

./hack/test-tool.sh atuin
```shell
+ ./arkade get atuin --arch x86_64 --os darwin --quiet
+ file /home/lbrdevcrypto/.arkade/bin/atuin
/home/lbrdevcrypto/.arkade/bin/atuin: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
+ rm /home/lbrdevcrypto/.arkade/bin/atuin
+ echo

+ ./arkade get atuin --arch x86_64 --os linux --quiet
+ file /home/lbrdevcrypto/.arkade/bin/atuin
/home/lbrdevcrypto/.arkade/bin/atuin: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3244ac15a5e31ca1926a41befa0b1017c1048fa8, for GNU/Linux 3.2.0, stripped
+ rm /home/lbrdevcrypto/.arkade/bin/atuin
+ echo
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hey thanks for the PR.

Please could you rebase all your commits down into one?

Here's how I do it: https://www.youtube.com/watch?v=8j0H6urZ-bU

Then - go ahead and do a final sign-off with `git commit -s --amend`

Alex

**Comment by alexellis** [comment]
Sounds like the upstream project won't be adding Arm support any time soon, so we'll go ahead as is. Just run the rebase and ping me when done please.

**Comment by lbrealdev** [comment]
Hi Alex,

I was able to follow your video (amazing tutorial) and rebase my commits.

If anything else needs to be done please let me know.

Regards.

**Comment by alexellis** [comment]
Just for future reference please wrap the commit message as per - https://cbea.ms/git-commit/amp/ and use your real name in the sign off text via git config.

**Review by alexellis — APPROVED** [review]
Approved but please see comment.

**Pull request merged**
