### PR TITLE
Use Latest Dashboard in Tekton App

### LINKED ISSUE #198: Use Latest Dashboard in Tekton App
The [Dashboard](https://github.com/tektoncd/pipeline) for the [Tekton App](https://github.com/alexellis/arkade/blob/master/cmd/apps/tekton_app.go) is uniquely versioned from the core [Tekton Pipelines](https://github.com/tektoncd/pipeline) service. It's currently outdated, and since it is independently versioned, I believe it should be removed altogether from the Tekton Pipelines installation.

## Expected Behaviour

While we could upgrade the version manually, or use "latest", I believe that this may be a good opportunity to drop the Dashboard from the Tekton installation. The Dashboard is an optional GUI accessory, and this may be better for Arkade users for multiple reasons: more important being a potential mismatch between the "latest" Pipelines release and the "latest" Dashboard release.

## Current Behaviour

We currently have the Dashboard version "0.5.1" hardcoded, which is incompatible with the newest versions of Pipelines.

## Possible Solution

I have made a PR, and will update this issue with the link.

(EDIT: PR #199)

## Context

I was showing arkade to my colleagues, and realized that the Dashboard was outdated, and is most likely unnecessary for Tekton Pipelines users (by default).

## Your Environment

* What Kubernetes distribution are you using?

Kind with Docker Desktop for macOS

```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
macOS 10.15.6
```

* What arkade version is this?

```
% arkade version
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Get Kubernetes apps the easy way

Version: 0.6.9
Git Commit: d538641dcc6895fe06c8843f60cb541dd13eb65b
```

### PR DESCRIPTION
**Pull request by nickgerace**
## Description

Tekton Dashboard releases are independently versioned from Tekton
Pipeline releases. Since Dashboard is an optional accessory to Tekton
Pipelines, this commit removes it altogether. This change was prompted
by the Dashboard version becoming incompatible with recent Tekton
Pipelines versions. The goal of this commit to ensure that Arkade users
have a consistently working version of Tekton at all times.

I've provided further context in the linked issues. Since the Tekton Dashboard service is an optional accessory, it may be best to only provide the core Tekton Pipelines service by default for a consistent user experience.

## Motivation and Context

Fixes #198 

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

The code was formatted, vetted, and then ```go test -v ./...``` was ran against it.

After a successful ```make build```, it was manually tested via a Kind cluster, on Docker Desktop, on macOS 10.15.6 (amd64).

Here is some STDOUT that shows it in action.

```
% kubectl get pods -A
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
kube-system          coredns-66bff467f8-8jgng                     1/1     Running   0          11m
kube-system          coredns-66bff467f8-s6qf5                     1/1     Running   0          11m
kube-system          etcd-kind-control-plane                      1/1     Running   0          11m
kube-system          kindnet-b4t9j                                1/1     Running   0          11m
kube-system          kube-apiserver-kind-control-plane            1/1     Running   0          11m
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   0          11m
kube-system          kube-proxy-585cm                             1/1     Running   0          11m
kube-system          kube-scheduler-kind-control-plane            1/1     Running   0          11m
local-path-storage   local-path-provisioner-bd4bb6b75-ljfrw       1/1     Running   0          11m

% ./arkade install tekton
Using kubeconfig: /Users/nick/.kube/config
Node architecture: "amd64"
Installing Tekton pipelines...
=======================================================================
= Tekton pipelines has been installed. =
=======================================================================

Want to launch a Tekton pipeline and see it in action?
Get one here: https://github.com/tektoncd/pipeline/tree/master/examples

For more information: https://github.com/tektoncd/pipeline

Thanks for using arkade!

% kubectl get pods -A
NAMESPACE            NAME                                           READY   STATUS    RESTARTS   AGE
kube-system          coredns-66bff467f8-8jgng                       1/1     Running   0          13m
kube-system          coredns-66bff467f8-s6qf5                       1/1     Running   0          13m
kube-system          etcd-kind-control-plane                        1/1     Running   0          14m
kube-system          kindnet-b4t9j                                  1/1     Running   0          13m
kube-system          kube-apiserver-kind-control-plane              1/1     Running   0          14m
kube-system          kube-controller-manager-kind-control-plane     1/1     Running   0          14m
kube-system          kube-proxy-585cm                               1/1     Running   0          13m
kube-system          kube-scheduler-kind-control-plane              1/1     Running   0          14m
local-path-storage   local-path-provisioner-bd4bb6b75-ljfrw         1/1     Running   0          13m
tekton-pipelines     tekton-pipelines-controller-7d5d5cc54f-nvlq9   1/1     Running   0          8s
tekton-pipelines     tekton-pipelines-webhook-5d9dc45569-cs78t      1/1     Running   0          8s

% ./arkade info tekton   
Info for app: tekton
Want to launch a Tekton pipeline and see it in action?
Get one here: https://github.com/tektoncd/pipeline/tree/master/examples

For more information: https://github.com/tektoncd/pipeline
```

Here is an example of a TaskRun in action. This leverages the Tekton Pipelines service. I copied the example from [my last PR](https://github.com/alexellis/arkade/pull/61) here.

```
% cat example.yaml 
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: example-taskrun
spec:
  taskSpec:
    steps:
      - name: ubuntu
        image: ubuntu:focal
        command:
          - echo
        args:
          - "Hello world!"

% kubectl create -f example.yaml 
taskrun.tekton.dev/example-taskrun created

% kubectl logs example-taskrun-pod-g2w5h step-ubuntu 
Hello world!

% kubectl get pods -n default 
NAME                        READY   STATUS      RESTARTS   AGE
example-taskrun-pod-g2w5h   0/1     Completed   0          32s
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

Thank you for looking this over!

### CODE REVIEW

**Comment by alexellis** [comment]
I've commented on #198

**Comment by nickgerace** [comment]
Changed the name based on our conversation.

**Formerly**: Remove Dashboard from Tekton App
**Currently**: Use Latest Dashboard in Tekton App

**Comment by nickgerace** [comment]
Hmm... I rebased with upstream and hit the following failure in the build. It does not appear to be related to my change, but I've seen stranger things happen. Would you happen to know @alexellis ?

```
[nick at mac in ~/repos/arkade] (0) (tekton)
% make test
CGO_ENABLED=0 go test github.com/alexellis/arkade github.com/alexellis/arkade/cmd github.com/alexellis/arkade/cmd/apps github.com/alexellis/arkade/pkg github.com/alexellis/arkade/pkg/apps github.com/alexellis/arkade/pkg/archive github.com/alexellis/arkade/pkg/config github.com/alexellis/arkade/pkg/env github.com/alexellis/arkade/pkg/get github.com/alexellis/arkade/pkg/helm github.com/alexellis/arkade/pkg/k8s github.com/alexellis/arkade/pkg/types -cover
?   	github.com/alexellis/arkade	[no test files]
?   	github.com/alexellis/arkade/cmd	[no test files]
ok  	github.com/alexellis/arkade/cmd/apps	0.173s	coverage: 1.5% of statements
?   	github.com/alexellis/arkade/pkg	[no test files]
?   	github.com/alexellis/arkade/pkg/apps	[no test files]
?   	github.com/alexellis/arkade/pkg/archive	[no test files]
ok  	github.com/alexellis/arkade/pkg/config	0.117s	coverage: 23.1% of statements
?   	github.com/alexellis/arkade/pkg/env	[no test files]
--- FAIL: Test_DownloadDarwin (0.50s)
    get_test.go:47: want: https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli-darwin, got: https://github.com/openfaas/faas-cli/releases/download/0.12.13/faas-cli-darwin
--- FAIL: Test_DownloadArmhf (0.41s)
    get_test.go:131: want: https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli-armhf, got: https://github.com/openfaas/faas-cli/releases/download/0.12.13/faas-cli-armhf
--- FAIL: Test_DownloadArm64 (0.40s)
    get_test.go:152: want: https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli-arm64, got: https://github.com/openfaas/faas-cli/releases/download/0.12.13/faas-cli-arm64
--- FAIL: Test_DownloadWindows (0.42s)
    get_test.go:173: want: https://github.com/openfaas/faas-cli/releases/download/0.12.9/faas-cli.exe, got: https://github.com/openfaas/faas-cli/releases/download/0.12.13/faas-cli.exe
FAIL
coverage: 41.4% of statements
FAIL	github.com/alexellis/arkade/pkg/get	1.978s
ok  	github.com/alexellis/arkade/pkg/helm	0.236s	coverage: 6.8% of statements
?   	github.com/alexellis/arkade/pkg/k8s	[no test files]
?   	github.com/alexellis/arkade/pkg/types	[no test files]
FAIL
make: *** [test] Error 1
```

**Comment by nickgerace** [comment]
Just rebased, and had successful test runs now. The behavior remains the same as above, but now the ```make test``` target works.

```bash
[nick at mac in ~/git/arkade] (0) (tekton)
% make build fmtcheck test
go build
make: Nothing to be done for `fmtcheck'.
CGO_ENABLED=0 go test github.com/alexellis/arkade github.com/alexellis/arkade/cmd github.com/alexellis/arkade/cmd/apps github.com/alexellis/arkade/pkg github.com/alexellis/arkade/pkg/apps github.com/alexellis/arkade/pkg/archive github.com/alexellis/arkade/pkg/config github.com/alexellis/arkade/pkg/env github.com/alexellis/arkade/pkg/get github.com/alexellis/arkade/pkg/helm github.com/alexellis/arkade/pkg/k8s github.com/alexellis/arkade/pkg/types -cover
?   	github.com/alexellis/arkade	[no test files]
?   	github.com/alexellis/arkade/cmd	[no test files]
ok  	github.com/alexellis/arkade/cmd/apps	0.100s	coverage: 1.6% of statements
?   	github.com/alexellis/arkade/pkg	[no test files]
?   	github.com/alexellis/arkade/pkg/apps	[no test files]
?   	github.com/alexellis/arkade/pkg/archive	[no test files]
ok  	github.com/alexellis/arkade/pkg/config	0.114s	coverage: 23.1% of statements
?   	github.com/alexellis/arkade/pkg/env	[no test files]
ok  	github.com/alexellis/arkade/pkg/get	(cached)	coverage: 39.4% of statements
ok  	github.com/alexellis/arkade/pkg/helm	(cached)	coverage: 6.8% of statements
?   	github.com/alexellis/arkade/pkg/k8s	[no test files]
?   	github.com/alexellis/arkade/pkg/types	[no test files]
```

**Comment by Waterdrips** [comment]
Hi @nickgerace are we pinning to a known version as per https://github.com/alexellis/arkade/issues/198#issuecomment-686963363 ? this PR currently uses "latest"

**Comment by nickgerace** [comment]
Hi @Waterdrips we are not. The issue that it _currently_ uses a specific version. In order to keep Tekton dashboards compatible with Tekton pipelines, we should either have both use "latest" or specific release versions.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
