### PR TITLE
tests: use baseURL to avoid string duplication

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

## Description
based on this request: https://github.com/alexellis/arkade/pull/498#discussion_r686579516 improving the tests to avoid string duplication

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Are you a GitHub Sponsor (Yes/No?)

- [x] Yes
- [ ] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by dirien** [comment]
@cpanato mental! ❤️

**Comment by alexellis** [comment]
I get the intent here, but I feel like it will make this actively harder to maintain, I usually copy the full URLs from the downloads page into the test as part of writing each app.

Sorry that you went to all this work without checking if it was wanted first.

**Comment by cpanato** [comment]
no problem @alexellis 
What do you have in mind to rewrite that?

**Comment by alexellis** [comment]
Closing might be the best course of action for now. Please do suggest big changes or refactoring in an issue in the future, I hate being the bad guy and having to say no.

**Pull request closed without merging**
