### PR TITLE
Add lazygit to list of tools

### LINKED ISSUE #729: Add lazygit to arkade get
Lazygit is simple terminal UI for git commands.
https://github.com/jesseduffield/lazygit

## Expected Behaviour

`arkade get lazygit` install lazygit

## Current Behaviour

Not implemented

## Are you a GitHub Sponsor yet (Yes/No?)

- [x] Yes
- [ ] No

## Possible Solution

Add lazygit as an installable cli tool.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Lazygit is a simple terminal UI for git commands. It simplifies the use of some powerful git features.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? 49,094
https://somsubhra.github.io/github-release-stats/?username=jesseduffield&repository=lazygit&page=1&per_page=5

## Your Environment

* What Kubernetes distribution are you using?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux cromulon 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* What arkade version is this?
```
Version: 0.8.30
Git Commit: f80689248728d4ba1385fb46d858fb494ffd5743
```

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Maria Kotlyarevskaya <mariia.kotliarevskaia@gmail.com>

Adds lazygit to list of tools

## Description
- Adds lazygit to list of tools
- Adds braces for `if (or` condition to be consistent across the `tools.go`

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

fixes #729 

## How Has This Been Tested?

```bash
./arkade get lazygit --arch arm64
./arkade get lazygit --arch x86_64
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Shikachuu — APPROVED** [review]
Can you run a manual test for all the available arch/oc combo and provide the output please?
(There is a great example script in `hack/test-dagger.sh`)

Otherwise LGTM!

**Comment by Jasstkn** [comment]
> Can you run a manual test for all the available arch/oc combo and provide the output please? (There is a great example script in `hack/test-dagger.sh`)
> 
> Otherwise LGTM!

Hey. Thank you for the quick review. I also think that it's a good point to add to `CONTRIBUTING.md` (script can be easily improved to `./test.sh <tool>`, replace all dagger -> `$1`)

Here is the output. 
```
./hack/test-dagger.sh lazygit
+ go build
+ ./arkade get lazygit --arch arm64 --os darwin --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
/Users/maria.kotlyarevskaya/.arkade/bin/lazygit: Mach-O 64-bit executable arm64
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
+ ./arkade get lazygit --arch x86_64 --os darwin --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
/Users/maria.kotlyarevskaya/.arkade/bin/lazygit: Mach-O 64-bit executable x86_64
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
+ ./arkade get lazygit --arch x86_64 --os linux --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
/Users/maria.kotlyarevskaya/.arkade/bin/lazygit: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=u9IXYxTNR0OJDWqaiGP4/S6QNaBF0qydmH3SLCMB-/vZfFskqjj5PvUzcUL3Td/SSzR1fUM27i-bCVFiiDf, stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
+ ./arkade get lazygit --arch arm64 --os linux --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
/Users/maria.kotlyarevskaya/.arkade/bin/lazygit: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=5bfJBhRStyO25Mks9H2k/CGwiXPIIbrr18iGchcxw/fGgZSCHhuvYWjOSg4ig-/Q1lnqmmA2Bkja8QrQ5OW, stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
+ ./arkade get lazygit --arch x86_64 --os ming --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
/Users/maria.kotlyarevskaya/.arkade/bin/lazygit: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=5bfJBhRStyO25Mks9H2k/CGwiXPIIbrr18iGchcxw/fGgZSCHhuvYWjOSg4ig-/Q1lnqmmA2Bkja8QrQ5OW, stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/lazygit
```

**Comment by Shikachuu** [comment]
Hey @Jasstkn, I like the idea, unfortunately, not every application shares the same OS/Arch combos, but if you have an idea , I think we would like to see a PR about that.

Either way, I'll update the `CONTRIBUTING.md` soon.

**Comment by alexellis** [comment]
We need a rebase before a merge can be perform.

**Comment by Jasstkn** [comment]
> @Jasstkn we need a rebase before a merge can be performed.

done.

**Comment by Jasstkn** [comment]
> Hey @Jasstkn, I like the idea, unfortunately, not every application shares the same OS/Arch combos, but if you have an idea , I think we would like to see a PR about that.
> 
> Either way, I'll update the `CONTRIBUTING.md` soon.

  At least if we improve this script and add instructions about running it, its input can be included to the PR. It allows reviewers to review all at once without requesting additional steps from contributors.

**Comment by alexellis** [comment]
Thank you @Jasstkn, your contribution made it into a release: https://github.com/alexellis/arkade/releases/tag/0.8.33

**Comment by Jasstkn** [comment]
> Thank you @Jasstkn, your contribution made it into a release: https://github.com/alexellis/arkade/releases/tag/0.8.33

Amazing! Thank you very much!

**Pull request merged**
