### PR TITLE
Add vault to list of tools

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Maria Kotlyarevskaya <mariia.kotliarevskaia@gmail.com>

Adds vault to available CLI tools as part of #627

## Description

Adds vault to arkade

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```bash
/hack/test-dagger.sh vault
+ go build
+ ./arkade get vault --arch arm64 --os darwin --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/vault
/Users/maria.kotlyarevskaya/.arkade/bin/vault: Mach-O 64-bit executable arm64
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/vault
+ ./arkade get vault --arch x86_64 --os darwin --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/vault
/Users/maria.kotlyarevskaya/.arkade/bin/vault: Mach-O 64-bit executable x86_64
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/vault
+ ./arkade get vault --arch x86_64 --os linux --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/vault
/Users/maria.kotlyarevskaya/.arkade/bin/vault: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ngbWiT7M23-nO4Aa-FjJ/FmrlyYuIQ-0laELD7Mdw/ndjygiXLeQLV3SjSYgYw/76l9xXwrEMLN4F7PPYUI, not stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/vault
+ ./arkade get vault --arch arm64 --os linux --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/vault
/Users/maria.kotlyarevskaya/.arkade/bin/vault: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=j1rrzgC1GJOt5fPiJcXV/6_iNlYEPNKeQNG8PTMo-/4lFYAUGLAIlAOhwjZ7EB/NB0qCxyJl_oIUhqeB3cx, not stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/vault
+ ./arkade get vault --arch x86_64 --os ming --quiet
🐳 arkade needs your support, learn more: https://my.arkade.dev
+ file /Users/maria.kotlyarevskaya/.arkade/bin/vault
/Users/maria.kotlyarevskaya/.arkade/bin/vault: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=j1rrzgC1GJOt5fPiJcXV/6_iNlYEPNKeQNG8PTMo-/4lFYAUGLAIlAOhwjZ7EB/NB0qCxyJl_oIUhqeB3cx, not stripped
+ rm /Users/maria.kotlyarevskaya/.arkade/bin/vault
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Shikachuu — APPROVED** [review]
LGTM!
Thanks for picking this up @Jasstkn, good job!

**Comment by Jasstkn** [comment]
@alexellis hi! Could you review this PR too? It's part of the issue about adding vault to arkade.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Thanks for this @Jasstkn 

We got "so far" along with the concept of "providers" for looking up versions that are not on GitHub - so to help with Helm, Hashicorp tools and Kubectl. I am not sure how far it got, but it might be useful for us to revisit, if you're interested?

#560

**Comment by Jasstkn** [comment]
> Thanks for this @Jasstkn 
> 
> 
> 
> We got "so far" along with the concept of "providers" for looking up versions that are not on GitHub - so to help with Helm, Hashicorp tools and Kubectl. I am not sure how far it got, but it might be useful for us to revisit, if you're interested?
> 
> 
> 
> #560 

I'll take a look and let you know there!

**Pull request merged**
