### PR TITLE
Allow get.sh to install to custom BINLOCATION

### PR DESCRIPTION
**Pull request by Liam-Deacon**
## Description
This allows users to avoid the need to have sudo to install arkade as they can download to their $HOME/bin

## Motivation and Context
Not all users can use `sudo`, so this change allows a slightly better experience for those users who simply wish to download and install `arkade` to another (user writable) location.

## How Has This Been Tested?
With the following bash command:
```bash
curl -sLS https://raw.githubusercontent.com/Liam-Deacon/arkade/master/get.sh | BINLOCATION=~/test-bin bash && \
test -d ~/test-bin && test -f ~/test-bin/arkade && \
echo "PASSED" || echo "FAILED"
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @Liam-Deacon 

Thanks for your interest, however we do not accept PRs unless the issue / problem / improvement has been discussed with a maintainer and approved for a change.

Alex

**Comment by alexellis** [comment]
> Not all users can use sudo, so this change allows a slightly better experience for those users who simply wish to download and install arkade to another (user writable) location.

The docs mention that if you leave off sudo, arkade is downloaded to `tmp`, then you should `mv` it yourself afterwards. I can't see a reason why that can't be scripted.

@Shikachuu can you confirm the above is correct?

Alex

**Comment by Shikachuu** [comment]
> > Not all users can use sudo, so this change allows a slightly better experience for those users who simply wish to download and install arkade to another (user writable) location.
> 
> The docs mention that if you leave off sudo, arkade is downloaded to `tmp`, then you should `mv` it yourself afterwards. I can't see a reason why that can't be scripted.
> 
> @Shikachuu can you confirm the above is correct?
> 
> Alex

It is correct indeed.
image

**Comment by alexellis** [comment]
@Shikachuu can you show the `cp` command working too?

**Comment by Shikachuu** [comment]
> @Shikachuu can you show the `cp` command working too?

image

**Comment by alexellis** [comment]
We didn't hear back from @Liam-Deacon, but have a method to do what he was asking for, so I'm marking this as resolved / wontfix.

**Pull request closed without merging**
