### PR TITLE
Add nats connector app

### LINKED ISSUE #112: [App] Add nats-connector to arkade
## Expected Behaviour

Add an app for the openfaas nats-connector helm chart to arkade, once complete openfaas users will be able to subscribe to events from NATS simply by running `arkade install nats-connector`

https://github.com/openfaas/faas-netes/tree/master/chart/nats-connector

### PR DESCRIPTION
**Pull request by viveksyngh**
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #112 

## How Has This Been Tested?

Tested on my local desktop with k3d

```
./bin/arkade-darwin install nats-connector -n openfaas
2020/06/17 14:18:31 Client: x86_64, Darwin
2020/06/17 14:18:31 User dir established as: /Users/viveks/.arkade/
map[]
"openfaas/nats-connector" has been added to your repositories

VALUES values.yaml
Command: /Users/viveks/.arkade/bin/helm3/helm [upgrade --install nats-connector openfaas/nats-connector --namespace openfaas --values /var/folders/tw/6ww2mtms12ndnypdycqfy_q40000gy/T/charts/nats-connector/values.yaml]
Release "nats-connector" does not exist. Installing it now.
NAME: nats-connector
LAST DEPLOYED: Wed Jun 17 14:18:38 2020
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thanks for installing nats-connector. Please follow the instructions below to get you started.

You can watch the Connector logs to see it invoke your functions:

$ kubectl logs -n openfaas deploy/nats-connector -f
=======================================================================
= nats-connector has been installed.                                   =
=======================================================================

# View the connector logs:

kubectl logs deploy/nats-connector -n openfaas -f

# Find out more on the project homepage:
https://github.com/openfaas/faas-netes/tree/master/chart/nats-connector


Thanks for using arkade!
➜  arkade git:(nats-connector) kubectl logs -n openfaas deploy/nats-connector -f
==============================================================================
NATS Connector for OpenFaaS

Gateway URL: http://gateway.openfaas:8080
NATS URL: nats://nats:4222
Topics: 30s
Upstream timeout: [nats-test]
Topic-map rebuild interval: 5s
Async invocation: "false"
==============================================================================

2020/06/17 08:48:39 Configured topics: [nats-test]
2020/06/17 08:48:39 Binding to topic: "nats-test"
2020/06/17 08:48:39 Subscription: nats-test ready

➜  arkade git:(nats-connector) export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
➜  arkade git:(nats-connector) faas-cli deploy --name receive-message --image openfaas/receive-message:latest --fprocess='./handler' --annotation topic="nats-test"
➜  arkade git:(nats-connector) kubectl port-forward -n openfaas svc/gateway 8080:8080 &
[1] 63950
➜  arkade git:(nats-connector) Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080

➜  arkade git:(nats-connector) faas-cli deploy --name receive-message --image openfaas/receive-message:latest --fprocess='./handler' --annotation topic="nats-test"
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Handling connection for 8080

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/receive-message

➜  arkade git:(nats-connector) faas-cli deploy --name publish-message --image openfaas/publish-message:latest --fprocess='./handler' --env nats_url=nats://nats.openfaas:4222
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Handling connection for 8080

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/publish-message

➜  arkade git:(nats-connector) faas-cli invoke publish-message <<< "test message"
Handling connection for 8080
Sent "test message"%                                                                                                                                                              ➜  arkade git:(nats-connector) kubectl logs -n openfaas deploy/nats-connector -f
==============================================================================
NATS Connector for OpenFaaS

Gateway URL: http://gateway.openfaas:8080
NATS URL: nats://nats:4222
Topics: 30s
Upstream timeout: [nats-test]
Topic-map rebuild interval: 5s
Async invocation: "false"
==============================================================================

2020/06/17 08:48:39 Configured topics: [nats-test]
2020/06/17 08:48:39 Binding to topic: "nats-test"
2020/06/17 08:48:39 Subscription: nats-test ready
2020/06/17 08:50:03 Topic: nats-test, message: "test message"
2020/06/17 08:50:03 Invoke function: figlet.openfaas-fn
2020/06/17 08:50:03 Invoke function: receive-message.openfaas-fn
2020/06/17 08:50:03 connector-sdk got result: [200] nats-test => figlet.openfaas-fn (372) bytes
2020/06/17 08:50:03 connector-sdk got result: [200] nats-test => receive-message.openfaas-fn (28) bytes
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by aidun** [comment]
I think there is something buggy with the pr. I setup a fresh k3d cluster and did an arkade install nats-connector.

It seems that the app didn't update the helm repo. Also the app didn't create an namespace if the --namespace flag is used. If someone can verify it, I will raise an issue.

**Comment by viveksyngh** [comment]
I created a new k3s cluster with k3d and installed openfaas and nats-connector, it worked fine. 

```
k3d create
INFO[0000] Created cluster network with ID ce2c5b1f6f5d39e37667a9308dafae25563b3f34b0fd5bbcd2090d2b067b273a
INFO[0000] Created docker volume  k3d-k3s-default-images
INFO[0000] Creating cluster [k3s-default]
INFO[0000] Creating server using docker.io/rancher/k3s:v1.17.2-k3s1...
INFO[0000] SUCCESS: created cluster [k3s-default]
INFO[0000] You can now use the cluster with:

export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
kubectl cluster-info
➜  arkade git:(nats-connector) export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
WARN[0000] Couldn't get the kubeconfig from cluster 'k3s-default': Maybe it's not ready yet and you can try again later.
FATA[0000]  Couldn't copy kubeconfig.yaml from server container 513b60fdad438e0c93d0c51957923ac25aac051f6261d18891d9c4eae65d7d51
Error: No such container:path: 513b60fdad438e0c93d0c51957923ac25aac051f6261d18891d9c4eae65d7d51:/output/kubeconfig.yaml
➜  arkade git:(nats-connector) export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
➜  arkade git:(nats-connector) kubectl cluster-info
Kubernetes master is running at https://localhost:6443
CoreDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://localhost:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
➜  arkade git:(nats-connector) arkade install openfaas --set basic_auth=true \  --set functionNamespace=openfaas-fn
Using kubeconfig: /Users/viveks/.config/k3d/k3s-default/kubeconfig.yaml
Using helm3
Node architecture: "amd64"
Client: "x86_64", "Darwin"
2020/06/17 23:03:35 User dir established as: /Users/viveks/.arkade/
"openfaas" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "inlets" chart repository
...Successfully got an update from the "nats-connector" chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "mqtt-connector" chart repository
...Successfully got an update from the "openfaas/nats-connector" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
VALUES values.yaml
Command: /Users/viveks/.arkade/bin/helm3/helm [upgrade --install openfaas openfaas/openfaas --namespace openfaas --values /var/folders/tw/6ww2mtms12ndnypdycqfy_q40000gy/T/charts/openfaas/values.yaml --set faasnetes.imagePullPolicy=Always --set basicAuthPlugin.replicas=1 --set serviceType=NodePort --set functionNamespace=openfaas-fn --set gateway.directFunctions=true --set operator.create=false --set openfaasImagePullPolicy=IfNotPresent --set gateway.replicas=1 --set queueWorker.replicas=1 --set basic_auth=true --set clusterRole=false]
Release "openfaas" does not exist. Installing it now.
NAME: openfaas
LAST DEPLOYED: Wed Jun 17 23:04:03 2020
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that openfaas has started, run:

  kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
=======================================================================
= OpenFaaS has been installed.                                        =
=======================================================================

# Get the faas-cli
curl -SLsf https://cli.openfaas.com | sudo sh

# Forward the gateway to your machine
kubectl rollout status -n openfaas deploy/gateway
kubectl port-forward -n openfaas svc/gateway 8080:8080 &

# If basic auth is enabled, you can now log into your gateway:
PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
echo -n $PASSWORD | faas-cli login --username admin --password-stdin

faas-cli store deploy figlet
faas-cli list

# For Raspberry Pi
faas-cli store list \
 --platform armhf

faas-cli store deploy figlet \
 --platform armhf

# Find out more at:
# https://github.com/openfaas/faas

Thanks for using arkade!
➜  arkade git:(nats-connector) kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas"
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
basic-auth-plugin   0/1     1            0           19s
prometheus          0/1     1            0           19s
queue-worker        0/1     1            0           19s
nats                0/1     1            0           19s
gateway             0/1     1            0           19s
faas-idler          0/1     1            0           19s
alertmanager        0/1     1            0           19s
➜  arkade git:(nats-connector) kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas" --watch
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
prometheus          0/1     1            0           25s
gateway             0/1     1            0           25s
alertmanager        0/1     1            0           25s
basic-auth-plugin   1/1     1            1           25s
queue-worker        1/1     1            1           25s
nats                1/1     1            1           25s
faas-idler          0/1     1            0           25s
faas-idler          1/1     1            1           26s
faas-idler          0/1     1            0           27s
alertmanager        1/1     1            1           43s
faas-idler          1/1     1            1           44s
faas-idler          0/1     1            0           45s
gateway             1/1     1            1           49s
prometheus          1/1     1            1           52s
^C%                                                                                                                                                                               ➜  arkade git:(nats-connector) kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas" --watch
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
basic-auth-plugin   1/1     1            1           60s
queue-worker        1/1     1            1           60s
nats                1/1     1            1           60s
alertmanager        1/1     1            1           60s
faas-idler          0/1     1            0           60s
gateway             1/1     1            1           60s
prometheus          1/1     1            1           60s
faas-idler          1/1     1            1           74s
^C%                                                                                                                                                                               ➜  arkade git:(nats-connector) kubectl -n openfaas get deployments -l "release=openfaas, app=openfaas" --watch
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
basic-auth-plugin   1/1     1            1           94s
queue-worker        1/1     1            1           94s
nats                1/1     1            1           94s
alertmanager        1/1     1            1           94s
gateway             1/1     1            1           94s
prometheus          1/1     1            1           94s
faas-idler          1/1     1            1           94s
^C%                                                                                                                                                                               ➜  arkade git:(nats-connector)
➜  arkade git:(nats-connector)
➜  arkade git:(nats-connector) ./bin/arkade-darwin install nats-connector -n openfaas
2020/06/17 23:05:53 Client: x86_64, Darwin
2020/06/17 23:05:53 User dir established as: /Users/viveks/.arkade/
"openfaas/nats-connector" has been added to your repositories

VALUES values.yaml
Command: /Users/viveks/.arkade/bin/helm3/helm [upgrade --install nats-connector openfaas/nats-connector --namespace openfaas --values /var/folders/tw/6ww2mtms12ndnypdycqfy_q40000gy/T/charts/nats-connector/values.yaml]
Release "nats-connector" does not exist. Installing it now.
NAME: nats-connector
LAST DEPLOYED: Wed Jun 17 23:05:58 2020
NAMESPACE: openfaas
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thanks for installing nats-connector. Please follow the instructions below to get you started.

You can watch the Connector logs to see it invoke your functions:

$ kubectl logs -n openfaas deploy/nats-connector -f
=======================================================================
= nats-connector has been installed.                                   =
=======================================================================

# View the connector logs:

kubectl logs deploy/nats-connector -n openfaas -f

# Find out more on the project homepage:
https://github.com/openfaas/faas-netes/tree/master/chart/nats-connector


Thanks for using arkade!
➜  arkade git:(nats-connector) kubectl logs -n openfaas deploy/nats-connector -f
==============================================================================
NATS Connector for OpenFaaS

Gateway URL: http://gateway.openfaas:8080
NATS URL: nats://nats:4222
Topics: 30s
Upstream timeout: [nats-test]
Topic-map rebuild interval: 5s
Async invocation: "false"
==============================================================================

2020/06/17 17:36:07 Configured topics: [nats-test]
2020/06/17 17:36:07 Binding to topic: "nats-test"
2020/06/17 17:36:07 Subscription: nats-test ready
```

**Comment by aidun** [comment]
Try using a another namespace with `—namespace=Test123`

**Comment by aidun** [comment]
I think it only works because you installed OpenFaaS at first and openfaas creates the openfaas namepspace. If you deploy nats-connector without using an already existing namespace it will run into an issue:

`
 ~/repo/arkade   43  k3d create                                                                                                                                                                                                     (43|…)
INFO[0000] Created cluster network with ID e35dccb43adff147726cde94c18c7868eaa58f4c9efbe3a2f9300481c043459d
INFO[0000] Created docker volume  k3d-k3s-default-images
INFO[0000] Creating cluster [k3s-default]
INFO[0000] Creating server using docker.io/rancher/k3s:latest...
INFO[0000] SUCCESS: created cluster [k3s-default]
INFO[0000] You can now use the cluster with:

export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"
kubectl cluster-info
 ~/repo/arkade   43  export KUBECONFIG="$(k3d get-kubeconfig --name='k3s-default')"                                                                                                                                                 (43|…)
 ~/repo/arkade   43  ./arkade install nats-connector --namespace test123                                                                                                                                                            (43|…)
2020/06/17 21:05:45 Client: x86_64, Darwin
2020/06/17 21:05:45 User dir established as: /Users/markushartmann/.arkade/
"openfaas/nats-connector" has been added to your repositories

VALUES values.yaml
Command: /Users/markushartmann/.arkade/bin/helm3/helm [upgrade --install nats-connector openfaas/nats-connector --namespace test123 --values /var/folders/nj/q4hj6sr17gzf6fxwrg74h_v80000gn/T/charts/nats-connector/values.yaml]
Release "nats-connector" does not exist. Installing it now.
Error: create: failed to create: namespaces "test123" not found
Error: exit code 1, stderr: Error: create: failed to create: namespaces "test123" not found
`

**Pull request merged**
