### PR TITLE
add skupper

### LINKED ISSUE #969: skupper support for arkade get
## Expected Behaviour

add [Skupper CLI](https://skupper.io) in arkade get

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

  Total Downloads 5,647

If approved, are you willing to submit a pull request for this?

YES

### PR DESCRIPTION
**Pull request by tuxtof**
## Description

Add skupper CLI

## Motivation and Context

- [X] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

Fix #969 

## How Has This Been Tested?

make e2e

```
=== RUN   Test_CheckTools/Download_of_skupper
=== PAUSE Test_CheckTools/Download_of_skupper
=== CONT  Test_CheckTools/Download_of_skupper
    --- PASS: Test_CheckTools/Download_of_skupper (0.57s)
```

hack/test-tool.sh skupper

```
+ ./arkade get skupper --arch arm64 --os darwin --quiet
+ file /Users/cris/.arkade/bin/skupper
/Users/cris/.arkade/bin/skupper: Mach-O 64-bit executable arm64
+ rm /Users/cris/.arkade/bin/skupper
+ echo

+ ./arkade get skupper --arch x86_64 --os darwin --quiet
+ file /Users/cris/.arkade/bin/skupper
/Users/cris/.arkade/bin/skupper: Mach-O 64-bit executable x86_64
+ rm /Users/cris/.arkade/bin/skupper
+ echo

+ ./arkade get skupper --arch x86_64 --os linux --quiet
+ file /Users/cris/.arkade/bin/skupper
/Users/cris/.arkade/bin/skupper: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=FMOZ3Cz5gBuYmWNBIr1h/YbfiH7MsoD_R7sBk8mO5/sQmBo1QNevjUCRyseo7e/doYyxsFn2STVMNSSnXjL, with debug_info, not stripped
+ rm /Users/cris/.arkade/bin/skupper
+ echo

+ ./arkade get skupper --arch aarch64 --os linux --quiet
+ file /Users/cris/.arkade/bin/skupper
/Users/cris/.arkade/bin/skupper: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=tozEh6CQt-s3s9u8f4NK/CvJvxQdw7Hwn5Xr7hHrL/kQN92-Mq1sW9ZWdNhYVA/6oIBUTky6x8ds15AIGhf, with debug_info, not stripped
+ rm /Users/cris/.arkade/bin/skupper
+ echo

+ ./arkade get skupper --arch x86_64 --os mingw --quiet
+ file /Users/cris/.arkade/bin/skupper.exe
/Users/cris/.arkade/bin/skupper.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /Users/cris/.arkade/bin/skupper.exe
+ echo
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]
LGTM 🔥

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Thanks for the PR @tuxtof

**Comment by tuxtof** [comment]
You are welcome @alexellis always a pleasure 🤗

**Pull request merged**
