### PR TITLE
Add Timoni CLI

### PR DESCRIPTION
**Pull request by stefanprodan**
## Description

This PR adds the [timoni](https://github.com/stefanprodan/timoni) binaries for Windows (AMD64), Linux (AMD64, ARM64) and macOS (AMD64, ARM64) to the Arkade tools.

## Motivation and Context

I want to make Timoni easily available to Linux and Windows users, and Arkade feels like the right tool for this. Once this PR is merge and released, I plan to add `arkade get timoni` to the Timoni [installation guide](https://timoni.sh/install/).

Currently Timoni advertises Homebrew (macOS) as the only installation method besides manually downloading the binaries from GitHub. 

## How Has This Been Tested?

```console
$ ./hack/test-tool.sh timoni
+ ./arkade get timoni --arch arm64 --os darwin --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: Mach-O 64-bit executable arm64
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os darwin --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: Mach-O 64-bit executable x86_64
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os linux --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=viHf1-t2G-D2aCcEMl40/dLNjxtgsyoNYmPqu9TME/7ZU5b5eL2LYuoMpuggLj/Rr41bWHEXnH3mU5eRL4s, stripped
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch aarch64 --os linux --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=h2qufTUKipY1dgb95kd9/4c33mBdXQgc8kq6biQp7/kofcXWa-88cAw7EmV-zf/koqYWwLU5M1zMKXSI6e-, stripped
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os ming --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=h2qufTUKipY1dgb95kd9/4c33mBdXQgc8kq6biQp7/kofcXWa-88cAw7EmV-zf/koqYWwLU5M1zMKXSI6e-, stripped
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for the PR. The last test case should return the exe

arkade get timoni --arch x86_64 --os ming --quiet

I wonder what's happening there? Could be that we need amd64 instead or mingw. Can you compare with your unit tests and faas-cli for Windows?

**Comment by stefanprodan** [comment]
Hmm not sure what's going on, but flux and eksctl also look broken on Windows, it returns `ARM aarch64` for `--arch x86_64 --os ming`

**Comment by stefanprodan** [comment]
I think I've found the bug, in downloadg.go there is:

```go
	finalName := tool.Name
	if strings.Contains(strings.ToLower(operatingSystem), "mingw") && !tool.NoExtension {
		finalName = finalName + ".exe"
	}
``` 

So test-tool.sh should have:

```
./arkade get $1 --arch x86_64 --os mingw --quiet && file $HOME/.arkade/bin/$1.exe && rm $HOME/.arkade/bin/$1.exe && echo
```

**Comment by stefanprodan** [comment]
With [c3afb65](https://github.com/alexellis/arkade/pull/888/commits/c3afb657ebeef54f4906ca7b1ebb059b799dd734):

```
$ ./hack/test-tool.sh timoni
+ ./arkade get timoni --arch arm64 --os darwin --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: Mach-O 64-bit executable arm64
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os darwin --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: Mach-O 64-bit executable x86_64
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os linux --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=viHf1-t2G-D2aCcEMl40/dLNjxtgsyoNYmPqu9TME/7ZU5b5eL2LYuoMpuggLj/Rr41bWHEXnH3mU5eRL4s, stripped
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch aarch64 --os linux --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni
/Users/stefanprodan/.arkade/bin/timoni: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=h2qufTUKipY1dgb95kd9/4c33mBdXQgc8kq6biQp7/kofcXWa-88cAw7EmV-zf/koqYWwLU5M1zMKXSI6e-, stripped
+ rm /Users/stefanprodan/.arkade/bin/timoni
+ echo

+ ./arkade get timoni --arch x86_64 --os mingw --quiet
+ file /Users/stefanprodan/.arkade/bin/timoni.exe
/Users/stefanprodan/.arkade/bin/timoni.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /Users/stefanprodan/.arkade/bin/timoni.exe
+ echo

```

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
There's a new release for this now.

**Comment by stefanprodan** [comment]
Awesome! Thanks Alex

**Pull request merged**
