### PR TITLE
feat: add vCluster CLI

### LINKED ISSUE #526: [CLI]: vCluster CLI support
[vCluster](https://github.com/loft-sh/vcluster)- Create fully functional virtual Kubernetes clusters - Each vcluster runs inside a namespace of the underlying k8s cluster. It's cheaper than creating separate full-blown clusters and it offers better multi-tenancy and isolation than regular namespaces.

Project Site: https://www.vcluster.com
Stars: 897
Contributors: 10
Slack Channel: https://slack.loft.sh/

## Expected Behaviour

```shell
$ arkade get vCluster
```

## Current Behaviour

There is no support for installing **vCluster** CLI.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [x] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

## Description
add vCluster CLI

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
Fixes #526 

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [x] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @developer-guy CI is failing for this PR, please can you take a look?

**Comment by developer-guy** [comment]
seems ok @alexellis

**Comment by developer-guy** [comment]
kindly ping @alexellis

**Comment by alexellis** [comment]
LGTM, thank you.

**Comment by alexellis** [comment]
We have a bunch of other PRs and issues that need someone to check them over and reply. Could you take a few minutes to review?

**Comment by developer-guy** [comment]
Of course ✌️

**Pull request merged**
