### PR TITLE
Fix `arkade get kustomize`

### PR DESCRIPTION
**Pull request by EnigmaCurry**
## Description
Various fixes for `get kustomize`. 

 * Fixes the version string and URLs to download
 * Adds linux arm64 os string (untested)

## Motivation and Context

I ran `arkade get kustomize --version=v3.8.8` and it failed, because the version 3.8.1 was hard-coded in the URL string. This is a fix for this.

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

I opened #299 

## How Has This Been Tested?
I changed the `get_test` suite to expect the corrected version URLs.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

I removed `kustomize/v3.8.1` as the version and replaced with `v3.8.1` without the `kustomize` part. But this seemed unavoidable due to the strange way they name their versions and files. I don't consider this a breaking change though, because it wasn't working before.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x ] I have signed-off my commits with `git commit -s`
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
> Adds linux arm64 os string (untested)

Would you like to test this? Perhaps a unit test would work?

Alex

**Comment by alexellis** [comment]
This worked OK for me, what do you feel is not working here? I would like to see you create an issue before raising a PR, if that's OK (especially since I can't repro)

```
alex@alex-nuc8:~$ arkade get kustomize
Downloading kustomize
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.8.1/kustomize_v3.8.1_linux_amd64.tar.gz
12.51 MiB / 12.51 MiB [------------------------------------------------] 100.00%
/tmp/kustomize kustomize
2021/01/08 15:57:25 extracted tarball into /tmp: 1 files, 0 dirs (307.605965ms)
Tool written to: /home/alex/.arkade/bin/kustomize

# Add (kustomize) to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/alex/.arkade/bin/kustomize

# Or install with:
sudo mv /home/alex/.arkade/bin/kustomize /usr/local/bin/

alex@alex-nuc8:~$ /home/alex/.arkade/bin/kustomize

Manages declarative configuration of Kubernetes.
See https://sigs.k8s.io/kustomize

Usage:
  kustomize [command]


```

**Review by alexellis — CHANGES_REQUESTED** [review]
We need an issue describing the problem, and I can't reproduce this. Help me understand the issue.

**Comment by EnigmaCurry** [comment]
Hi, I had opened #299 to describe the problem. The problem is that the ONLY version that arkade can download is v3.8.1, even if I pass a version flag (because this is hard coded into the URL). I have tested that amd64 works with this PR, but I can't test ARM right now, so I'll close this PR for now. Thanks.

**Comment by alexellis** [comment]
Ok that's why we need issues creating with the full template filled out. Can you do that if you haven't already?

**Comment by ben-uptycs** [comment]
It would be nice if this was fixed so that users could install the latest version of Kustomize, rather than only v3.8.1.
What do you need to better understand what's happening here @alexellis? Seems like a fairly straitforward issue and @EnigmaCurry's fix looks good. Just replacing a hardcoded version string with the proper variable.

**Comment by alexellis** [comment]
We were missing admin on the template and testing. I'm open to having another look at this when I get a few cycles.

**Comment by jonico** [comment]
@alexellis:  at the moment, `arkade get kustomize` is nroken by the changes introduced in https://github.com/alexellis/arkade/commit/6a810bf2d441c2af1846ea5e96359ef3069570ba:

```
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.0.0/kustomize_v3.8.1_linux_amd64.tar.gz
Error: check with the vendor whether this tool is available for your system: incorrect status for downloading tool: 404
```

**Comment by jonico** [comment]
I will create a new PR with @EnigmaCurry 's changes, resolving merge conflicts and fixed tests in a moment ...

**Pull request closed without merging**
