### PR TITLE
Fixes #43: Add redis app

### LINKED ISSUE #43: Add app for Redis
## App

Redis, via Bitnami's chart

This is only available for amd64

https://github.com/bitnami/charts/tree/master/upstreamed/redis

### PR DESCRIPTION
**Pull request by aidun**
Fixes #43: Add redis app

- Helm3 only
- No arm support

## Description

Add the bitnami redis chart as app.

## Motivation and Context

#43 

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

non ARM:
```
arkade install redis
export REDIS_PASSWORD=$(kubectl get secret --namespace redis redis -o jsonpath="{.data.redis-password}" | base64 --decode)
kubectl run --namespace redis redis-client --rm --tty -i --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image docker.io/bitnami/redis:5.0.7-debian-10-r48 -- bash
redis-cli -a $REDIS_PASSWORD redis-master
# here you should be connected to the master
```
ARM:
```
arkade install redis
> Node architecture: "arm64"
> Error: only Intel, i.e. PC architecture is supported for this app
```

Intel: k3d on amd64 host
ARM: k3sup on raspi

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @aidun we'll require another rebase on this please.

See also the PR for the nats-connector in #126 - it simplifies the install and may be useful for you to follow too.

Alex

**Comment by aidun** [comment]
Okay. I will do it tomorrow afternoon. Should be easy if I don’t mess up my git again

**Comment by aidun** [comment]
I did the change. I had to add a function to the InstallerOptions to make it possible configure the --update-repo option

**Comment by alexellis** [comment]
Thank you @aidun - we will now need a rebase, please be careful not to create a merge commit.

Alex

**Comment by aidun** [comment]
Done

**Comment by alexellis** [comment]
Thank you for this :) We also need some more arkade tools for `arkade get` - such as kubeseal would be nice to add next if you wanted to take a look at how it all works?

**Comment by aidun** [comment]
I will go for it this weekend 😊

**Pull request merged**
