### PR TITLE
Fixes #42: Prevent installation of minio on armhf

### LINKED ISSUE #42: Prevent installation of minio on armhf
## Description

Prevent installation of minio on armhf since no images are available at this time upstream.

## Solution

Check the way we do this for the Istio app.

### PR DESCRIPTION
**Pull request by aidun**
Prevent installation of minio on armhf

## Description
Prevent installation of minio on armhf

## Motivation and Context

#42 

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Sorry I missed that you didn't complete the paperwork.

> How Has This Been Tested?

Can you show output of testing please?

**Comment by aidun** [comment]
Yes, I will do it tomorrow morning. Have to setup my PIs for this

________________________________
Von: Alex Ellis <notifications@github.com>
Gesendet: Monday, March 9, 2020 9:19:32 PM
An: alexellis/arkade <arkade@noreply.github.com>
Cc: Markus Hartmann <markush1986@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [alexellis/arkade] Fixes #42: Prevent installation of minio on armhf (#45)


Sorry I missed that you didn't complete the paperwork.

How Has This Been Tested?

Can you show output of testing please?

**Comment by aidun** [comment]
Yes, I will do it tomorrow morning. Have to setup my PIs for this.

________________________________
Von: Alex Ellis <notifications@github.com>
Gesendet: Monday, March 9, 2020 9:19:32 PM
An: alexellis/arkade <arkade@noreply.github.com>
Cc: Markus Hartmann <markush1986@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [alexellis/arkade] Fixes #42: Prevent installation of minio on armhf (#45)


Sorry I missed that you didn't complete the paperwork.

How Has This Been Tested?

Can you show output of testing please?

**Comment by aidun** [comment]
Arm64:
image

amd64:
image

Is this okay?

**Pull request merged**
