### PR TITLE
Add Alex's hey fork

### PR DESCRIPTION
**Pull request by Shikachuu**
## Description
Replace the old `hey` with @alexellis's new fork.

## Motivation and Context
Replace the old `hey` with @alexellis's new fork.

## How Has This Been Tested?
Added unit tests to cover the changes, also run the e2e tests, all of them passed.

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Interesting.. I tried getting hey and kept getting a 404 / tool not found. Perhaps because I was on M1.

**Comment by alexellis** [comment]
Approved

**Comment by alexellis** [comment]
Can you run a test like with did for dagger, with quiet output?

**Comment by Shikachuu** [comment]
```
+ go build
+ ./arkade get hey --arch arm64 --os darwin --quiet
+ file /home/shika/.arkade/bin/hey
/home/shika/.arkade/bin/hey: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=4jIAzUwVK6PQjIAhUtZx/R9PzlqMYW0JwHhhN_e9T/bdeu5lHWE2FGXU5398x7/wuIWIUCQ-AIDqpZAumyb, stripped
+ rm /home/shika/.arkade/bin/hey
+ ./arkade get hey --arch x86_64 --os darwin --quiet
+ file /home/shika/.arkade/bin/hey
/home/shika/.arkade/bin/hey: Mach-O 64-bit x86_64 executable
+ rm /home/shika/.arkade/bin/hey
+ ./arkade get hey --arch x86_64 --os linux --quiet
+ file /home/shika/.arkade/bin/hey
/home/shika/.arkade/bin/hey: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=4jIAzUwVK6PQjIAhUtZx/R9PzlqMYW0JwHhhN_e9T/bdeu5lHWE2FGXU5398x7/wuIWIUCQ-AIDqpZAumyb, stripped
+ rm /home/shika/.arkade/bin/hey
+ ./arkade get hey --arch arm64 --os linux --quiet
+ file /home/shika/.arkade/bin/hey
/home/shika/.arkade/bin/hey: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=4jIAzUwVK6PQjIAhUtZx/R9PzlqMYW0JwHhhN_e9T/bdeu5lHWE2FGXU5398x7/wuIWIUCQ-AIDqpZAumyb, stripped
+ rm /home/shika/.arkade/bin/hey
+ ./arkade get hey --arch x86_64 --os ming --quiet
+ file /home/shika/.arkade/bin/hey
/home/shika/.arkade/bin/hey: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /home/shika/.arkade/bin/hey
```

**Comment by alexellis** [comment]
Hmm, three of them have the same CPU architecture. It could be the template or my builder repo getting things wrong

**Pull request merged**
