### PR TITLE
Add KubeSphere CLI

### PR DESCRIPTION
**Pull request by LinuxSuRen**
## Description
Hi team, I'm a maintainer of the [KubeSphere](https://github.com/kubesphere) community. [ks](https://github.com/kubesphere-sigs/ks) is the CLI of [KubeSphere](https://github.com/kubesphere/kubesphere) which is a container platform tailored for Kubernetes multi-cloud, datacenter, and edge management.

Given [ks](https://github.com/kubesphere-sigs/ks) still on the fast development path. We put it in a SIG level of GitHub organization.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [x] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, thanks for your interest in arkade.

You will need to read the message that Derek sent you and action that, there's also a merge conflict, so can you rebase against the master branch too?

https://www.youtube.com/watch?v=8j0H6urZ-bU

Thanks,
Alex

**Review by alexellis — CHANGES_REQUESTED** [review]
See the notes from Derek, we cannot merge the PR otherwise.

**Comment by LinuxSuRen** [comment]
I don't want to expose my email. Is that possible?

**Comment by alexellis** [comment]
Unfortunately the DCO does not allow for anonymous commits, we need a declaration from you and a contact address.

https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin

Let us know what you want to do, there are many OSS projects which require a valid email address, what do you do there?

**Comment by Shikachuu** [comment]
Hey @LinuxSuRen
Do you still have interest to fix the DCO error and continue your PR?

**Comment by LinuxSuRen** [comment]
Sorry about the delay. I'm not going to spend more time maintaining it anymore. So, I'm going to close this PR. Sorry for any possible trouble
.

**Pull request closed without merging**
