### PR TITLE
Update cosign to v1.2.0

### PR DESCRIPTION
**Pull request by cpanato**
## Description
Update cosign to v1.2.0
 
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```
$ make build

$ ./arkade get cosign
Downloading: cosign
Downloading: https://github.com/sigstore/cosign/releases/download/v1.2.0/cosign-darwin-amd64
67.78 MiB / 67.78 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/var/folders/cz/_mkxxyx97n38b5p0hs3n2j2m0000gn/T/cosign-darwin-amd64 written.
2021/09/15 09:57:23 Copying /var/folders/cz/_mkxxyx97n38b5p0hs3n2j2m0000gn/T/cosign-darwin-amd64 to /Users/cpanato/.arkade/bin/cosign
Tool written to: /Users/cpanato/.arkade/bin/cosign

# Add (cosign) to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/Users/cpanato/.arkade/bin/cosign

# Or install with:
sudo mv /Users/cpanato/.arkade/bin/cosign /usr/local/bin/

$ /Users/cpanato/.arkade/bin/cosign version
GitVersion:    v1.2.0
GitCommit:     aa5d23b86d09c2275dd3a7317b7c98cc30a8eee7
GitTreeState:  clean
BuildDate:     '2021-09-14T22:57:11Z'
GoVersion:     go1.17
Compiler:      gc
Platform:      darwin/amd64
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [ ] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by dirien** [comment]
@cpanato, this time i resisted and waited 😄

**Comment by alexellis** [comment]
The reason we needed a pinned version is because there are development tags set to "full releases" and not pre-release. I raised an issue to track this.

If fixed upstream we won't have to update versions manually going forward: https://github.com/sigstore/cosign/issues/585

I see that it's now closed, @cpanato do you want to try removing the version to see what happens?

**Comment by cpanato** [comment]
removed and tested again, worked!

```
$ ./arkade get cosign
Downloading: cosign
2021/09/15 10:45:14 Looking up version for cosign
2021/09/15 10:45:14 Found: v1.2.0
Downloading: https://github.com/sigstore/cosign/releases/download/v1.2.0/cosign-darwin-amd64
67.78 MiB / 67.78 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/var/folders/cz/_mkxxyx97n38b5p0hs3n2j2m0000gn/T/cosign-darwin-amd64 written.
2021/09/15 10:45:17 Looking up version for cosign
2021/09/15 10:45:17 Found: v1.2.0
2021/09/15 10:45:17 Copying /var/folders/cz/_mkxxyx97n38b5p0hs3n2j2m0000gn/T/cosign-darwin-amd64 to /Users/cpanato/.arkade/bin/cosign
Tool written to: /Users/cpanato/.arkade/bin/cosign

# Add (cosign) to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/Users/cpanato/.arkade/bin/cosign

# Or install with:
sudo mv /Users/cpanato/.arkade/bin/cosign /usr/local/bin/
```

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
@dirien your dreams have come true 😉 

But there are some tools that continue to need manual updates because they exist "off GitHub", so would you mind updating the HashiCorp tools?

**Pull request merged**
