### PR TITLE
Add Hubble CLI to arkade get

### PR DESCRIPTION
**Pull request by recollir**
## Description

Added the _hubble_ cli to `arkade get`

## Motivation and Context

I have raised #703 which was given the go ahead in this [comment](https://github.com/alexellis/arkade/issues/703#issuecomment-1166565654). _Hubble_ can also be seen as the companion cli to the _cilium_ cli that was added with PR #707.

## How Has This Been Tested?

Output of the unit test:

```
❯ go test -v -run Test_DownloadHubble
=== RUN   Test_DownloadHubble
=== RUN   Test_DownloadHubble/darwin_x86_64_v0.10.0
=== RUN   Test_DownloadHubble/darwin_arm64_v0.10.0
=== RUN   Test_DownloadHubble/linux_x86_64_v0.10.0
=== RUN   Test_DownloadHubble/linux_aarch64_v0.10.0
=== RUN   Test_DownloadHubble/ming_x86_64_v0.10.0
--- PASS: Test_DownloadHubble (0.00s)
    --- PASS: Test_DownloadHubble/darwin_x86_64_v0.10.0 (0.00s)
    --- PASS: Test_DownloadHubble/darwin_arm64_v0.10.0 (0.00s)
    --- PASS: Test_DownloadHubble/linux_x86_64_v0.10.0 (0.00s)
    --- PASS: Test_DownloadHubble/linux_aarch64_v0.10.0 (0.00s)
    --- PASS: Test_DownloadHubble/ming_x86_64_v0.10.0 (0.00s)
```

Output of `make e2e`:

```
❯ make e2e|fgrep hubble
=== RUN   Test_CheckTools/Download_of_hubble
=== PAUSE Test_CheckTools/Download_of_hubble
=== CONT  Test_CheckTools/Download_of_hubble
    --- PASS: Test_CheckTools/Download_of_hubble (0.76s)
```

Output of the _dagger_ script:

image

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
Thanks for working with us to get this in :+1:

**Comment by recollir** [comment]
🙌 Anything else I could look at and give it a try?

**Comment by Shikachuu** [comment]
Hey @recollir,
It would be great if you could give a try to update the Mongodb helm chart as [briefly described here.](https://github.com/alexellis/arkade/issues/274#issuecomment-1179155875)
Or you could give a try to update the min.io chart as described [here](https://helm.min.io/) to the non-operator one.

If you would like to work with CLI tools again there are a couple of unresolved old issues: [like this](https://github.com/alexellis/arkade/issues/243) or [this which can be a chart + a cli tool.](https://github.com/alexellis/arkade/issues/627)

**Pull request merged**
