### PR TITLE
Add rabbitmq app

### PR DESCRIPTION
**Pull request by DavidIsa**
Signed-off-by: David Isayan <disayan8@gmail.com>

## Description
Support the installation of Rabbitmq for Kuberenetes

## Motivation and Context

- [x] I have raised an issue to propose this change [#485](https://github.com/alexellis/arkade/issues/485#issue-953206375)

## How Has This Been Tested?

The rabbitmq app was tested manually on Ubuntu pc.
`arkade install rabbitmq` command installed the rabbitmq service properly. 
I've not been able to test the app on ARM, so for ARM I disabled it. 

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM :1st_place_medal: 

Are there other apps you'd like to submit like Cassandra or NATS 2.0?

**Comment by alexellis** [comment]
@DavidIsa could you look into the build error from CI?

**Comment by DavidIsa** [comment]
@alexellis It was a formatting issue, I pushed a fix for it.

**Comment by DavidIsa** [comment]
@alexellis  I will add Cassandra. I've created an issue for it [#491](https://github.com/alexellis/arkade/issues/491)

**Comment by alexellis** [comment]
Approving CI to run for this commit.. please ping me with the status.

**Comment by alexellis** [comment]
I just rebased the commit for the list of apps in the README

**Pull request merged**
