### PR TITLE
Include ktop cli

### LINKED ISSUE #894: Add ktop
## Add a new CLI for download

ktop

A top-like tool for your Kubernetes clusters

Releases - https://github.com/vladimirvivien/ktop/releases

### PR DESCRIPTION
**Pull request by nitishkumar71**
## Description

Ktop CLI has been included in arkade
## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
Closes #894 

## How Has This Been Tested?

1. Install ktop using `./arkade get ktop`
2. Produced Output
```
Downloading: ktop
2023/04/30 23:31:23 Looking up version for ktop
2023/04/30 23:31:23 Found: v0.3.5
Downloading: https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_linux_amd64.tar.gz
11.43 MiB / 11.43 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/ktop_v0.3.5_linux_amd64.tar.gz written.
2023/04/30 23:31:26 Looking up version for ktop
2023/04/30 23:31:26 Found: v0.3.5
2023/04/30 23:31:26 Extracted: /tmp/ktop
2023/04/30 23:31:26 Copying /tmp/ktop to /home/nitishkumar/.arkade/bin/ktop

Wrote: /home/nitishkumar/.arkade/bin/ktop (38.62MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/nitishkumar/.arkade/bin/ktop

# Or install with:
sudo mv /home/nitishkumar/.arkade/bin/ktop /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
@nitishkumar71 please could you rebase?

And also run as per - https://github.com/alexellis/arkade/blob/master/hack/test-tool.sh

**Comment by nitishkumar71** [comment]
Result of `test-tool.sh` 

```
+ ./arkade get ktop --arch arm64 --os darwin --quiet
+ file /home/nitishkumar/.arkade/bin/ktop
/home/nitishkumar/.arkade/bin/ktop: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
+ rm /home/nitishkumar/.arkade/bin/ktop
+ echo

+ ./arkade get ktop --arch x86_64 --os darwin --quiet
+ file /home/nitishkumar/.arkade/bin/ktop
/home/nitishkumar/.arkade/bin/ktop: Mach-O 64-bit x86_64 executable
+ rm /home/nitishkumar/.arkade/bin/ktop
+ echo

+ ./arkade get ktop --arch x86_64 --os linux --quiet
+ file /home/nitishkumar/.arkade/bin/ktop
/home/nitishkumar/.arkade/bin/ktop: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=JUWccy2AbIytViC1aFZq/HQg4kq7RyKxV77htJTiy/ov1iELsZ280YfueMdhI8/W7_vphuEyrj6wEoxDZIc, stripped
+ rm /home/nitishkumar/.arkade/bin/ktop
+ echo

+ ./arkade get ktop --arch aarch64 --os linux --quiet
+ file /home/nitishkumar/.arkade/bin/ktop
/home/nitishkumar/.arkade/bin/ktop: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=JlKrX30W6uoUGwcStrGg/o_GERPzDlgTGc_LU0o3g/2KapnGHF6v3aW_NPqAZV/GFhQmnv5lvoEZqYbf6OR, stripped
+ rm /home/nitishkumar/.arkade/bin/ktop
+ echo

+ ./arkade get ktop --arch x86_64 --os mingw --quiet

The requested version of ktop is not available or configured in arkade for mingw/x86_64

* Check if a binary is available from the project for your Operating System
* View the ktop releases page: https://github.com/vladimirvivien/ktop/releases
* Feel free to raise an issue at https://github.com/alexellis/arkade/issues for help

Error: server returned status: 404
````

As there is no windows binary so the last error is expected.

**Comment by nitishkumar71** [comment]
Result of `./arkade get ktop` after rebase

```
Downloading: ktop
2023/05/27 16:58:01 Looking up version for ktop
2023/05/27 16:58:01 Found: v0.3.5
Downloading: https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_linux_amd64.tar.gz
11.43 MiB / 11.43 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/arkade-1263702459/ktop_v0.3.5_linux_amd64.tar.gz written.
2023/05/27 16:58:04 Looking up version for ktop
2023/05/27 16:58:04 Found: v0.3.5
2023/05/27 16:58:04 Extracted: /tmp/arkade-1263702459/ktop
2023/05/27 16:58:04 Copying /tmp/arkade-1263702459/ktop to /home/nitishkumar/.arkade/bin/ktop

Wrote: /home/nitishkumar/.arkade/bin/ktop (38.62MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/nitishkumar/.arkade/bin/ktop

# Or install with:
sudo mv /home/nitishkumar/.arkade/bin/ktop /usr/local/bin/

🐳 arkade needs your support: https://github.com/sponsors/alexellis
```

**Comment by nitishkumar71** [comment]
@alexellis Branch is rebased now.

**Comment by alexellis** [comment]
Thanks very much :smile:

**Pull request merged**
