### PR TITLE
Add `sops` to downloadable tools in `arkade get`

### PR DESCRIPTION
**Pull request by Shikachuu**
## Description
SOPS is a secret management service by Mozilla.

## Motivation and Context

- [X] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md)) #648 

## How Has This Been Tested?
Created unit tests, also ran `arkade get sops` with the `--os` and `--arch` flags.

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Rerunning all jobs. This appears to be related to #649

**Comment by Shikachuu** [comment]
> Rerunning all jobs. This appears to be related to #649

It is, but I need to rebase this and all my other branches.

**Comment by Shikachuu** [comment]
> > Rerunning all jobs. This appears to be related to #649
> 
> It is, but I need to rebase this and all my other branches.

@alexellis Rebase done :heavy_check_mark:

**Comment by alexellis** [comment]
Thank you

**Pull request merged**
