### PR TITLE
add gucci to arkade get

### PR DESCRIPTION
**Pull request by karthick-kk**
Signed-off-by: karthick-kk <kkzone@gmail.com>

Related to https://github.com/alexellis/arkade/issues/644, it adds the gucci cli tool to arkade get

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

After build, tried to pull the binaries for different os with `arkade get --arch --os` and arch and validated the binary compatibility with `file` command.

```
❯ file /home/kk/.arkade/bin/gucci
/home/kk/.arkade/bin/gucci: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6s6NCJgJyZtxYNGIvs0q/QCx3gLkZz2akEN9TB6pC/BbsW9bARrFwczaU-W9Yq/fiA172a0vGXS74DQWNfT, not stripped
❯ file /home/kk/.arkade/bin/gucci
/home/kk/.arkade/bin/gucci: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=Kp17E3hOvAJQ3ko473mL/CtFZEovJfwoAE89az_YK/fEM3qbeFAjZhm6Rgaeot/mwnbXjwQSpr2CX1ib1ds, not stripped
❯ file /home/kk/.arkade/bin/gucci
/home/kk/.arkade/bin/gucci: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
❯ file /home/kk/.arkade/bin/gucci
/home/kk/.arkade/bin/gucci: Mach-O 64-bit x86_64 executable
❯ file /home/kk/.arkade/bin/gucci
/home/kk/.arkade/bin/gucci: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
@karthick-kk 

>I have raised an issue to propose this change, which has been given a label of design/approved by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

You may have jumped the gun here. We didn't discuss or approve this submission.

Alex

**Comment by karthick-kk** [comment]
> @karthick-kk
> 
> > I have raised an issue to propose this change, which has been given a label of design/approved by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
> 
> You may have jumped the gun here. We didn't discuss or approve this submission.
> 
> Alex
Yes, but this can wait if there are priorities to go in for the next release. Would you mind adding it to backlog, I'll rebase when it gets approved. Thanks.

**Comment by alexellis** [comment]
This PR needs to be rebased before we can merge it.

**Comment by alexellis** [comment]
Please feel free to reopen this when you're ready to rebase it.

**Pull request closed without merging**
