### PR TITLE
Remove helm 2

### PR DESCRIPTION
**Pull request by Amalkh5**
## Description

This PR will remove helm 2 support from Arkade.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
I tested the changes by installing each app on k8s cluster but I could not put it here because it would be too long 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
@Amalkh5 please could you rebase re: the change I made in Nginx?

**Comment by Amalkh5** [comment]
@alexellis done

**Comment by alexellis** [comment]
Merged, thank you 👍

**Pull request merged**
