### PR TITLE
Akash Network CLI tool 

### PR DESCRIPTION
**Pull request by 88plug**
## Description
Add [Akash Network](https://akash.network) CLI

## Motivation and Context
Easier access to cloud compute resources.

## How Has This Been Tested?
Yes

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X ] I have signed-off my commits with `git commit -s`

- [X ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
> How has this been tested?

"Yes" is not an answer to this question. As I mentioned on your issue, look at a past PR to see what we expect 

You should also see commands in our PR template. Not sure if you redacted them?

Cc @Shikachuu

**Comment by alexellis** [comment]
See this example by @Jasstkn, which includes what we're looking for:

https://github.com/alexellis/arkade/pull/769

See also: https://github.com/alexellis/arkade/blob/master/hack/test-tool.sh

**Comment by 88plug** [comment]
Thank you for the feedback - I will update accordingly

**Comment by alexellis** [comment]
We also need a real name for the DCO, which is why Derek won't accept the PR.

If you need someone else from your team to send the PR, that's also OK, as long as they author the commits and sign them off. Signing off isn't the same as a GPG signature.

**Comment by 88plug** [comment]
> We also need a real name for the DCO, which is why Derek won't accept the PR.
> 
> If you need someone else from your team to send the PR, that's also OK, as long as they author the commits and sign them off. Signing off isn't the same as a GPG signature.

Derek is no longer with Ovrclk/Akash.

**Comment by alexellis** [comment]
Hey @88plug I'm closing this as I assume you're not interseted in continuing with it.

Please feel free to reach out to me alex@openfaas.com and CC Greg about us adding it for you along with the Helm charts for Akash as a sponsored app.

Alex

**Pull request closed without merging**
