### PR TITLE
Add porter CLI to arkade

### LINKED ISSUE #457: [CLI] Porter
image

Add the Porter CLI to arkade.

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Context

What is Porter?
Take everything you need to do a deployment, the application itself and the entire process to deploy it: command-line tools, configuration files, secrets, and bash scripts to glue it all together. Package that into a versioned bundle distributed over standard Docker registries or plain tgz files.

Now anyone can install your application without deep knowledge of your deployment process, or following a step-by-step deployment doc, regardless of the tech stack.

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri engin.diri@mail.schwarz

## Description
Add Porter CLI to arkade

## Motivation and Context

Fixes #457
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```bash
$ docker container run --rm -v $(pwd):/workspace -ti golang:1.16.6-alpine sh
# cd /workspace
# go build
# ./arkade get nova
```
image

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
@dirien you were right, one of these PRs needed a quick rebase, could you do the honours?

**Comment by dirien** [comment]
@alexellis : done :)

**Comment by alexellis** [comment]
Approved, thank you @dirien 👍

**Pull request merged**
