### PR TITLE
Use GOARCH and GOOS

### PR DESCRIPTION
**Pull request by sheerun**
## Description
Uses go-native way to get arch and os instead of executing commands

## Motivation and Context
Less code, faster, probably supports windows

## How Has This Been Tested?
I've compiled and run arkade

### CODE REVIEW

**Comment by sheerun** [comment]
signoff is not necessary if all commits are squash-merged..

**Comment by sheerun** [comment]
Also without PHP signing how you can even tell it would be genuine? The best proof that I've sent this PR and code is because I'm using mine GitHub account to send this PR. Linux needs sign-offs because they accept patches via e-mail, not GitHub.

**Comment by alexellis** [comment]
Hi thanks for your interest in this project. Please can you read the contribution guide? I think you may have misunderstood the message from the bot given your comment. Signed off by is required for all contributions.

New changes and refactoring should be proposed before worked on too. A simple GitHub issue is fine. 

Alex

**Comment by sheerun** [comment]
Sorry not worth the effort

**Comment by alexellis** [comment]
No problems, if you change your mind, it's a single command and you're done. Everyone has to follow the same contributing guide and we've had over 250 people in the community do that so far across all the OSS projects managed by the OpenFaas community. 

```
git commit -s --amend
```

**Pull request closed without merging**
