### PR TITLE
fix: Fix version of kustomize

### LINKED ISSUE #595: kustomize failing on Linux AMD64
## Expected Behaviour

kustomize should continue to work

## Current Behaviour

It's failing to download for me on Linux / AMD64:

```bash
arkade get kustomize
Downloading: kustomize
2021/12/14 17:23:10 Looking up version for kustomize
2021/12/14 17:23:11 Found: v0.13.0
Downloading: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv0.13.0/kustomize_v0.13.0_linux_amd64.tar.gz
Error: incorrect status for downloading tool: 404
```

Let's get it fixed?

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri engin.diri@mail.schwarz

## Description

The problem is, that kustomize is a repo with different tools and different tags

So https://github.com/kubernetes-sigs/kustomize/releases/latest will lead to a different tool tag combination. Somtimes it can work, when kustomize was the latest but most of the time it will lead into errors!

So, I needed to add the version pack again into the tool list.

Fixes #595

## Motivation and Context

- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```sh
 docker container run --rm -v $(pwd):/workspace -ti golang:1.17 bash
root@475a61e4f405:/go# cd /workspace/
root@475a61e4f405:/workspace# go build .
go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/alexellis/go-execute v0.5.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/cheggaaa/pb/v3 v3.0.8
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-runewidth v0.0.12
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/fatih/color v1.10.0
go: downloading golang.org/x/crypto v0.0.0-20210711020723-a769d52b0f97
go: downloading github.com/sethvargo/go-password v0.2.0
go: downloading golang.org/x/mod v0.5.1
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
go: downloading github.com/rivo/uniseg v0.2.0
root@475a61e4f405:/workspace# ./arkade get kustomize
Downloading: kustomize
Downloading: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.1/kustomize_v4.4.1_linux_amd64.tar.gz
4.40 MiB / 4.40 MiB [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
/tmp/kustomize_v4.4.1_linux_amd64.tar.gz written.
/tmp/kustomize kustomize
2021/12/24 15:07:59 extracted tarball into /tmp: 1 files, 0 dirs (97.6151ms)
2021/12/24 15:07:59 Extracted: /tmp/kustomize
2021/12/24 15:07:59 Copying /tmp/kustomize to /root/.arkade/bin/kustomize

Tool written to: /root/.arkade/bin/kustomize

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/root/.arkade/bin/kustomize

# Or install with:
sudo mv /root/.arkade/bin/kustomize /usr/local/bin/
root@475a61e4f405:/workspace# mv /root/.arkade/bin/kustomize /usr/local/bin/
root@475a61e4f405:/workspace# kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}
root@475a61e4f405:/workspace# 
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by jdinsel-xealth** [comment]
This PR introduced a consistency issue versus many of the other versions that can be configured.

For example, kubeconform may be configured as `kubeconform: v0.6.2` in the arkade-get GitHub Action. `kustomize` must not specify the `v` character because of this pull request. The error shown in the GitHub action doesn't show the URL, so it may be difficult to determine what the issue is. Running `arkade get` on the CLI does output the URL.

**Comment by alexellis** [comment]
Hi @jdinsel-xealth

Glad to hear you are using arkade.

Do you want to go ahead and send a PR for how you'd like this to work?

Alex

**Comment by dirien** [comment]
@alexellis happy to do a PR too now if needed!

**Comment by alexellis** [comment]
Hey @dirien please don't feel like you need to ask for permission to send PRs to fix stuff :smile:

**Pull request merged**
