### PR TITLE
Add keploy via arkade

### PR DESCRIPTION
**Pull request by Sonichigo**
## Description
This PR attempts to add support for downloading and installing the `Keploy` for supported platforms (Linux, MacOS, Windows).

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I have tested on MacOs and WSL (for combined testing for windows and linux)
```
## wsl
go run . get keploy 

## macos
go run . get keploy --arch arm64
```

If updating or adding a new CLI to `arkade get`, run:

```
go build && ./hack/test-tool.sh keploy
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [x] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by Sonichigo** [comment]
@alexellis we have added the installation method:- https://keploy.io/docs/server/installation/#with-arkade

**Comment by Sonichigo** [comment]
@Shikachuu @Jasstkn  can you provide the feedback on this PR?

**Comment by alexellis** [comment]
Hi thanks for becoming a sponsor.

This looks good, however the git history needs cleaning up.

I see two commits and the second just says "s squash", we want only one.

If you want to make the job easier for yourself, create a new fork/branch, and copy paste the diff from his PR into your new one and do a single commit with "git commit -s" if you get something wrong, run "git commit -s --amend" then git push with `--force`

Can you explain the included flyctl change? I didn't see the e2e tests failing and you don't mention it in your PR description.

**Comment by Sonichigo** [comment]
Flyctl changes came from here - https://github.com/alexellis/arkade/pull/1091/commits/6c1c87ef10e0334668908f33f2a53fc85557fd0b . previously those were failing the testcases i just kept their changes. Have updated it my pr.

**Comment by alexellis** [comment]
Thanks for the PR :+1: I'll be cutting a release so it should be available shortly, after `arkade update`

**Comment by alexellis** [comment]
I've done this for you in https://github.com/alexellis/arkade/commit/2c0eb2175f664381e4a5cc4600ddbb85a005c298

It seems like the templates and the tests were both wrong, but in your original PR they seemed to be correct.

**Comment by Sonichigo** [comment]
> I've done this for you in [2c0eb21](https://github.com/alexellis/arkade/commit/2c0eb2175f664381e4a5cc4600ddbb85a005c298)
> 
> It seems like the templates and the tests were both wrong, but in your original PR they seemed to be correct.

Thanks! I was working to fix those! Thanks a lot @alexellis

**Pull request merged**
