### PR TITLE
Add terrascan CLI

### PR DESCRIPTION
**Pull request by yankeexe**
Signed-off-by: Yankee Maharjan <yankee.exe@gmail.com>

## Description

Add Terrascan CLI. 
It detects compliance and security violations across Infrastructure as Code to mitigate risk before provisioning cloud-native infrastructure.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Added Test Case `Test_DownloadTerrascan`. 

Tested on Linux amd64 and Linux arm64.

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
@yankeexe we need a quick rebase on this please

@dirien I also noticed that you didn't regenerate the README in your PR (unless I missed it) #499

**Review by alexellis — APPROVED** [review]
Approved, but please rebase so that I can merge.

**Comment by yankeexe** [comment]
> Approved, but please rebase so that I can merge.

@alexellis done! We can merge this.

**Comment by dirien** [comment]
@alexellis , not sure what you mean with regenerate the README? I added the tool into the readme -> #498

**Comment by alexellis** [comment]
We have another conflict on this one, sorry, but you will need to rebase.

**Comment by alexellis** [comment]
FYI this is still pending

**Comment by yankeexe** [comment]
@alexellis Ready for merge!

**Comment by Shikachuu** [comment]
@yankeexe can you rebase again please?

**Comment by Shikachuu** [comment]
@yankeexe are you still intrested to finish this PR using the new repository and a rebase?

**Comment by yankeexe** [comment]
@Shikachuu ready for merge!

**Comment by alexellis** [comment]
This requires a rebase due to the age, and other PRs having being merged recently.

**Comment by alexellis** [comment]
Closed in a1f31ad83c82e8501269ddbd7f90c454095aa709

**Pull request closed without merging**
