### PR TITLE
Add GitLab to Arkade

### PR DESCRIPTION
**Pull request by Johannestegner**
## Description

I will update this text with more information when the PR is closer to ready.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Work in progress for the following issue: #163 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @Johannestegner - I got your message on Slack asking for input.

When thinking about the flags, I ask: what’s the most minimal configuration that you can install? (and if possible, disable persistence by default also, but make sure there is a flag to enable it)

**Comment by Johannestegner** [comment]
> When thinking about the flags, I ask: what’s the most minimal configuration that you can install? (and if possible, disable persistence by default also, but make sure there is a flag to enable it)

Minimal in the sense of lowest amount of workload or lowest amount of "work" for a fully working one?

Let me give you an example:

It's a lot less strain on the cluster to disable pgsql, but if you do that, you have to configure an external pgsql instance which you then have to add configuration in the helm chart to connect to. (in this case, I feel like letting pgsql be installed by default is a good choice, while allowing disabling it as a flag might be a good idea), the same with minio and redis.

When it comes to persistence. If disabling, it should likely be disabled for every pod (or rather, every micro-service that uses volumes by default), I'm thinking that allowing to disable it over all or enabling it over all with a global flag might be a decent idea, but then again... who would install GitLab without any persistent volumes? hehee

---

So, the most minimal configuration for the user to have  a fully running and persistent GitLab installation is to by default install it all (while the ip and domain are <required> for the helm chart to install at all), while this would _not_ be the most minimal for the cluster. :)

**Comment by Johannestegner** [comment]
Sorry for totally forgetting about this PR, I have had quite a busy time for a while and this just disappeared from my mind!

I've rebased it with the master branch in this repository and fixed some minor things that had changed in the codebase, I do think it's quite ready for review now.

**Comment by alexellis** [comment]
Merged in https://github.com/alexellis/arkade/pull/252

@Johannestegner please can you double check the app still works as expected, and also look at the versions / flags etc?

**Comment by Johannestegner** [comment]
> @Johannestegner please can you double check the app still works as expected, and also look at the versions / flags etc?

For sure, need to finish of a few minor tasks for work, then I'll make sure it works still! :)

**Pull request closed without merging**
