### PR TITLE
feat: add duplik8s to tools

### PR DESCRIPTION
**Pull request by rgee0**
## Description

Adds https://github.com/Telemaco019/duplik8s to the growing list of tools

## Motivation and Context
- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer 

Via Discord

### Functional
```sh
➜  arkade git:(addDuplik8s) ✗ ./arkade get duplik8s
Downloading: duplik8s
2024/10/17 12:14:27 Looking up version for duplik8s
2024/10/17 12:14:28 Found: v0.3.0
Downloading: https://github.com/Telemaco019/duplik8s/releases/download/v0.3.0/duplik8s_Darwin_arm64.tar.gz
12.61 MiB / 12.61 MiB [----------------------------------------------------------------------] 100.00%
/var/folders/22/3b_f27kj3s37lbfqz_fq44jw0000gp/T/arkade-2789515258/duplik8s_Darwin_arm64.tar.gz written.
2024/10/17 12:14:29 Extracted: /var/folders/22/3b_f27kj3s37lbfqz_fq44jw0000gp/T/arkade-2789515258/duplik8s
2024/10/17 12:14:29 Copying /var/folders/22/3b_f27kj3s37lbfqz_fq44jw0000gp/T/arkade-2789515258/duplik8s to /Users/rgee0/.arkade/bin/duplik8s

Wrote: /Users/rgee0/.arkade/bin/duplik8s (46.71MB)

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/Users/rgee0/.arkade/bin/duplik8s

# Or install with:
sudo mv /Users/rgee0/.arkade/bin/duplik8s /usr/local/bin/

👏 Say thanks for arkade and sponsor Alex via GitHub: https://github.com/sponsors/alexellis
```

### make E2E
```sh
➜  arkade git:(addDuplik8s) ✗ make e2e > test.out
CGO_ENABLED=0 go test github.com/alexellis/arkade/pkg/get -cover --tags e2e -v
...
--- PASS: Test_CheckTools (0.00s)
    --- PASS: Test_CheckTools/Download_of_duplik8s (0.73s)
...
PASS
coverage: 61.4% of statements
ok  	github.com/alexellis/arkade/pkg/get	11.531s	coverage: 61.4% of statements

```

### test-tool
```sh
➜  arkade git:(addDuplik8s) ✗ ./hack/test-tool.sh duplik8s
+ ./arkade get duplik8s --arch arm64 --os darwin --quiet
+ file /Users/rgee0/.arkade/bin/duplik8s
/Users/rgee0/.arkade/bin/duplik8s: Mach-O 64-bit executable arm64
+ rm /Users/rgee0/.arkade/bin/duplik8s
+ echo

+ ./arkade get duplik8s --arch x86_64 --os darwin --quiet
+ file /Users/rgee0/.arkade/bin/duplik8s
/Users/rgee0/.arkade/bin/duplik8s: Mach-O 64-bit executable x86_64
+ rm /Users/rgee0/.arkade/bin/duplik8s
+ echo

+ ./arkade get duplik8s --arch x86_64 --os linux --quiet
+ file /Users/rgee0/.arkade/bin/duplik8s
/Users/rgee0/.arkade/bin/duplik8s: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=y3Leo-OfMJcO-ikPC46I/KjPZv73j3bxEn4yI3kvl/CJJPnaOsiP5Nti1Md1Zd/dN8xw9AgFLsJyxeTGKet, stripped
+ rm /Users/rgee0/.arkade/bin/duplik8s
+ echo

+ ./arkade get duplik8s --arch aarch64 --os linux --quiet
+ file /Users/rgee0/.arkade/bin/duplik8s
/Users/rgee0/.arkade/bin/duplik8s: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=OwaYoEzMgemddHpU5Ksz/h7EYBrrJ3-LDdfCV_V5s/8FJSDwwvOussNlZt8tgF/5Hk3YgeI_7k1PG1klMF2, stripped
+ rm /Users/rgee0/.arkade/bin/duplik8s
+ echo

+ ./arkade get duplik8s --arch x86_64 --os mingw --quiet
+ file /Users/rgee0/.arkade/bin/duplik8s.exe
/Users/rgee0/.arkade/bin/duplik8s.exe: PE32+ executable (console) x86-64, for MS Windows
+ rm /Users/rgee0/.arkade/bin/duplik8s.exe
+ echo
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
@rgee0 do you mind rebasing this for merge?

**Comment by rgee0** [comment]
Will do. AFK for much of the day

**Comment by rgee0** [comment]
Rebased

**Pull request merged**
