### PR TITLE
Add app for kong-ingress

### PR DESCRIPTION
**Pull request by nitishkumar71**
Add Support of [Kong ingress](https://github.com/Kong/kubernetes-ingress-controller) as an app
## Description

1. Included a new file to add Kong ingress as an application.
2. Included into install command list
3. Included into info command list
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
It will complete #235 

## How Has This Been Tested?

1. run ``` make test ```, all existing test cases passed
2. created build using ```make build```
3. installed Kong Ingress using ```arkade install kong-ingress```
4. Followed the [Getting started with Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/getting-started.md)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by nitishkumar71** [comment]
@Waterdrips Can you please review it?

**Comment by alexellis** [comment]
Thanks for the PR. Pinging @Waterdrips for a review.

**Review by Waterdrips — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
Thank you 👍 

Would you like to look at #234 next?

**Comment by nitishkumar71** [comment]
> Thank you +1
> 
> Would you like to look at #234 next?

Sure. I would.

**Pull request merged**
