### PR TITLE
Add Github CLI

### LINKED ISSUE #216: [App] Add GitHub CLI (gh)
## Task

Add an App for the GitHub CLI (gh)

https://github.com/cli/cli/

https://github.com/cli/cli/releases

This is useful for users of GitHub - for making PRs/referencing issues etc.

### PR DESCRIPTION
**Pull request by rberrelleza**
Fixes #216 
## Description

Install the Github CLI v1.0.0 with arkade

## Motivation and Context

- [x ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Added automation, and manually tested on MacOS, linux and arm64.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by rberrelleza** [comment]
What do you think @alexellis ?

**Comment by alexellis** [comment]
Sounds good. I can take a look at the weekend

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
FYI Derek responds to `/add label: label1,label2`, but only to users listed in .DEREK.yml

**Pull request merged**
