### PR TITLE
feat(tools): add oh-my-posh

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
## Description
Add oh-my-posh as a tool to install

## Motivation and Context
I want a straightforward way for people to install oh-my-posh using a no nonsense tool and this is exactly that.

## How Has This Been Tested?
I validated the install manually on Darwin and Windows

## Are you a GitHub Sponsor

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Hey @JanDeDobbeleer please add unit tests for this. See the example for docker-compose for instance, which I added today into master.

Alex

**Comment by JanDeDobbeleer** [comment]
@alexellis done

**Comment by Shikachuu** [comment]
> @alexellis done

Also can you verify that we can download all the binaries for all systems?
You can use the `--arch` and `--os` as described in the help tab:
image

**Comment by JanDeDobbeleer** [comment]
@Shikachuu validated.

**Comment by alexellis** [comment]
Hey @JanDeDobbeleer by validated, @Shikachuu means he'd like to see console output for each variation.

Use the `file` command to show the architecture of each binary, then add this to your "how has this been tested" in the PR.

For instance:

```
file /usr/local/bin/arkade
/usr/local/bin/arkade: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=oM879vWsutxGwbCrLcpZ/bLo8OrHdxj7XdqXEjpf9/_lXlbo3XbCaR4cqxbzQ0/KWha1LOeIptZBO2wO8vL, stripped
```

Alex

**Review by alexellis — APPROVED** [review]
Approving the PR, please see the comments from community.

**Comment by JanDeDobbeleer** [comment]
> he'd like to see console output for each variation

@alexellis OK, in that case I have to start again. Can't this validation be added as an Action? Seems like a good candidate to provide log output for common variations.

**Comment by alexellis** [comment]
You do not need to start again, you simply need to run arkade get -arch X -os Y a few times followed by the file command.

I expect it to take you 90 seconds. Unless we're not explaining this well enough?

**Comment by alexellis** [comment]
I've put up a PR for dagger to show you what we're looking for when we say, validate the URLs download the correct binaries. It's a one-time, thing. Thank you.

https://github.com/alexellis/arkade/pull/657

**Review by Shikachuu — APPROVED** [review]
Manual file downloads are fine.
Checked with this script (based on @alexellis's):
```bash
#!/bin/bash

set -e -x -u -o pipefail

go build 

./arkade get oh-my-posh --arch aarch64 --os darwin
file $HOME/.arkade/bin/oh-my-posh
rm $HOME/.arkade/bin/oh-my-posh

./arkade get oh-my-posh --arch x86_64 --os darwin
file $HOME/.arkade/bin/oh-my-posh
rm $HOME/.arkade/bin/oh-my-posh 

./arkade get oh-my-posh --arch x86_64 --os linux
file $HOME/.arkade/bin/oh-my-posh
rm $HOME/.arkade/bin/oh-my-posh 

./arkade get oh-my-posh --arch aarch64 --os linux
file $HOME/.arkade/bin/oh-my-posh
rm $HOME/.arkade/bin/oh-my-posh 

./arkade get oh-my-posh --arch amd64 --os ming
file $HOME/.arkade/bin/oh-my-posh
rm $HOME/.arkade/bin/oh-my-posh
```
Can you rebase this @JanDeDobbeleer, so we can merge it?

**Comment by alexellis** [comment]
@Shikachuu can you confirm the correct binaries were created by providing the output from the script you ran?

@JanDeDobbeleer we just need a rebase from you now, and then can merge. We're going to cut a release today, so it'd be good to have this in.

**Comment by Shikachuu** [comment]
> @Shikachuu can you confirm the correct binaries were created by providing the output from the script you ran?
> 
> @JanDeDobbeleer we just need a rebase from you now, and then can merge. We're going to cut a release today, so it'd be good to have this in.

Sure
```sh
Downloading: oh-my-posh
Downloading: https://github.com/jandedobbeleer/oh-my-posh/releases/download/v7.57.1/posh-darwin-arm64
/tmp/posh-darwin-arm64 written.

Tool written to: /home/shika/.arkade/bin/oh-my-posh

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/shika/.arkade/bin/oh-my-posh

# Or install with:
sudo mv /home/shika/.arkade/bin/oh-my-posh /usr/local/bin/
/home/shika/.arkade/bin/oh-my-posh: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
Downloading: oh-my-posh
Downloading: https://github.com/jandedobbeleer/oh-my-posh/releases/download/v7.57.1/posh-darwin-amd64
/tmp/posh-darwin-amd64 written.

Tool written to: /home/shika/.arkade/bin/oh-my-posh

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/shika/.arkade/bin/oh-my-posh

# Or install with:
sudo mv /home/shika/.arkade/bin/oh-my-posh /usr/local/bin/
/home/shika/.arkade/bin/oh-my-posh: Mach-O 64-bit x86_64 executable
Downloading: oh-my-posh
Downloading: https://github.com/jandedobbeleer/oh-my-posh/releases/download/v7.57.1/posh-linux-amd64
/tmp/posh-linux-amd64 written.

Tool written to: /home/shika/.arkade/bin/oh-my-posh

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/shika/.arkade/bin/oh-my-posh

# Or install with:
sudo mv /home/shika/.arkade/bin/oh-my-posh /usr/local/bin/
/home/shika/.arkade/bin/oh-my-posh: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=M_EHGnuu22fYiMSfkjR0/gkNj1Fs7LjRjfYGUrHMI/E5bzXCQcCxmgv_ZcVmXV/SylHmELUMzOM2wNrPtp_, stripped
Downloading: oh-my-posh
Downloading: https://github.com/jandedobbeleer/oh-my-posh/releases/download/v7.57.1/posh-linux-arm64
/tmp/posh-linux-arm64 written.

Tool written to: /home/shika/.arkade/bin/oh-my-posh

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/shika/.arkade/bin/oh-my-posh

# Or install with:
sudo mv /home/shika/.arkade/bin/oh-my-posh /usr/local/bin/
/home/shika/.arkade/bin/oh-my-posh: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=B7YQp812Kc6jqIZIa1xu/6hbp_YSfxBu4_0x9Z_r0/lCsPRJ520oZ24ylpIQK9/2N8z8NHsErRtOF28zPiw, stripped
Downloading: oh-my-posh
Downloading: https://github.com/jandedobbeleer/oh-my-posh/releases/download/v7.57.1/posh-windows-amd64.exe
/tmp/posh-windows-amd64.exe written.

Tool written to: /home/shika/.arkade/bin/oh-my-posh

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/shika/.arkade/bin/oh-my-posh

# Or install with:
sudo mv /home/shika/.arkade/bin/oh-my-posh /usr/local/bin/
/home/shika/.arkade/bin/oh-my-posh: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by JanDeDobbeleer** [comment]
@alexellis @Shikachuu done.

**Review by alexellis — APPROVED** [review]
The output looks good, thank you.

**Comment by alexellis** [comment]
Another rebase was needed after merging #572, so to make things a little easier for you @JanDeDobbeleer, I rebased your change into master. This PR will be closed, but you will see your commit in git under 3f7686bea7ab80572611a8763667a631670c8493

**Pull request closed without merging**
