### PR TITLE
Add Cilium CLI to arkade get

### PR DESCRIPTION
**Pull request by recollir**
## Description
Added the _cilium_ cli to `arkade get`

## Motivation and Context
I have raised issue #702 which was given the go ahead in this [comment](https://github.com/alexellis/arkade/issues/702#issuecomment-1165318385)

## How Has This Been Tested?

Output of unit test:
```
❯ go test -v -run Test_DownloadCilium
=== RUN   Test_DownloadCilium
=== RUN   Test_DownloadCilium/darwin_x86_64_v0.11.9
=== RUN   Test_DownloadCilium/darwin_arm64_v0.11.9
=== RUN   Test_DownloadCilium/linux_x86_64_v0.11.9
=== RUN   Test_DownloadCilium/linux_aarch64_v0.11.9
=== RUN   Test_DownloadCilium/ming_x86_64_v0.11.9
--- PASS: Test_DownloadCilium (0.00s)
    --- PASS: Test_DownloadCilium/darwin_x86_64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/darwin_arm64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/linux_x86_64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/linux_aarch64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/ming_x86_64_v0.11.9 (0.00s)
```

Output of `make e2e`:
```
❯ make e2e | fgrep cilium
=== RUN   Test_CheckTools/Download_of_cilium
=== PAUSE Test_CheckTools/Download_of_cilium
=== CONT  Test_CheckTools/Download_of_cilium
    --- PASS: Test_CheckTools/Download_of_cilium (0.60s)
```

Output of the _dagger_ script:
image

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by recollir** [comment]
@Shikachuu This is now the PR based on the discussion from #701

**Review by Shikachuu — APPROVED** [review]
Good job, now everything check, thanks for your effort!

**Comment by alexellis** [comment]
Hi, we need a rebase on this due to a another PR being merged.

**Comment by alexellis** [comment]
We'll need a rebase on this one now.

Thanks

**Comment by recollir** [comment]
@alexellis Done. Verified the e2e and unit test after the rebase.

```
❯ make e2e|fgrep cilium
=== RUN   Test_CheckTools/Download_of_cilium
=== PAUSE Test_CheckTools/Download_of_cilium
=== CONT  Test_CheckTools/Download_of_cilium
    --- PASS: Test_CheckTools/Download_of_cilium (0.91s)
```
❯ cd pkg/get && go test -v -run Test_DownloadCilium
=== RUN   Test_DownloadCilium
=== RUN   Test_DownloadCilium/darwin_x86_64_v0.11.9
=== RUN   Test_DownloadCilium/darwin_arm64_v0.11.9
=== RUN   Test_DownloadCilium/linux_x86_64_v0.11.9
=== RUN   Test_DownloadCilium/linux_aarch64_v0.11.9
=== RUN   Test_DownloadCilium/ming_x86_64_v0.11.9
--- PASS: Test_DownloadCilium (0.00s)
    --- PASS: Test_DownloadCilium/darwin_x86_64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/darwin_arm64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/linux_x86_64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/linux_aarch64_v0.11.9 (0.00s)
    --- PASS: Test_DownloadCilium/ming_x86_64_v0.11.9 (0.00s)
PASS
ok  	github.com/alexellis/arkade/pkg/get	0.564s
```

**Comment by alexellis** [comment]
Thanks for contributing arkade. 

It takes a considerable amount of time and energy to maintain arkade, so please consider helping us by becoming a sponsor via GitHub.

You'll find a big button on the repo and a link in the README file.

**Pull request merged**
