### PR TITLE
Updating pr template

### PR DESCRIPTION
**Pull request by kadern0**
Updating PR template
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Just merged two questions into one N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [ ] New application can be installed on ARM platform.
- [ ] New application shows an error message if the architecture is not supported.

### CODE REVIEW

**Comment by alexellis** [comment]
Seems like we have a rebase conflict, but the change is fine for me.

**Comment by kadern0** [comment]
I've solved the conflict from the web and don't know why Derek still doesn't like the PR.

**Comment by alexellis** [comment]
Sorry you haven't corrected the rebase issue.

Can you just open a new PR from a fresh branch, it's such a simple change after all.

**Comment by kadern0** [comment]
Closing this one as I opened another one for this, that has no conflicts.

**Pull request closed without merging**
