### PR TITLE
Add Redpanda's rpk tool to `arakde get`

### LINKED ISSUE #682: Feature request: add `rpk` to `arkade get`
The Redpanda Keeper (`rpk`) is Redpanda's CLI utility. `rpk` commands allow you to configure and manage Redpanda clusters, tune them for better performance, manage topics and groups, manage access control lists (ACLs), and more.

## Expected Behaviour

Future example output:
```
> arkade get rpk
Downloading: rpk
Downloading: https://github.com/redpanda-data/redpanda/releases/download/v22.1.1/rpk-linux-amd64.zip
12.4 MiB / 12.4 MiB [----------------------------------------------------------------------] 100.00%
/tmp/rpk-linux-amd64.zip written.
/tmp/rpk rpk
2022/01/19 12:06:22 unzipped archive into /tmp: 1 files, 0 dirs (487.370723ms)
2022/01/19 12:06:22 Unzipped: /tmp/rpk
2022/01/19 12:06:22 Copying /tmp/rpk to /home/user/.arkade/bin/rpk

Tool written to: /home/user/.arkade/bin/rpk

# Add arkade binary directory to your PATH variable
export PATH=$PATH:$HOME/.arkade/bin/

# Test the binary:
/home/user/.arkade/bin/rpk

# Or install with:
sudo mv /home/user/.arkade/bin/rpk /usr/local/bin/
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

I haven't looked into this yet, but I'll start the conversation with my colleagues and broader org.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? ~205K

If `rpk` is approved then we myself or someone else from Redpanda would create the PR for adding it to the tool.
One reason why I'm hoping to get `rpk` added is because I use this tool all the time, and I know it would simplify our documentation at https://docs.redpanda.com/. Once added, I can then more easily bring in the doc team and show them how `arkade` commands can replace more complicated steps (installing our CLI, cert-manager, etc.) throughout our site.

## Your Environment
The goal would be to `ark get rpk` on the following platforms (Windows not yet supported):
```
darwin-amd64
darwin-arm64
linux-amd64
darwin-arm64
```

Not sure the below details are too relevant, since this is just my local laptop.

* What Kubernetes distribution are you using?

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
> uname -a                 
Linux laptop 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> cat /etc/os-release  
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* What arkade version is this?

```
> arkade version                      
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.8.23
Git Commit: be5a8cc594cbe860055ede8ec36635fcf36ae283

 🐳 arkade needs your support, learn more: https://my.arkade.dev
```

### PR DESCRIPTION
**Pull request by Shikachuu**
## Description
Add `rpk` to `arkade get`

## Motivation and Context

- [X] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
Resolves #682 

## How Has This Been Tested?
Covered with unit tests and the usual shell script, see the PR comments for the result.

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by Shikachuu** [comment]
[Screencast from 2022-08-11 19:20:13.webm](https://user-images.githubusercontent.com/32636587/184218916-40ab5f97-d071-4708-8c8f-a6ae015dddfb.webm)

**Comment by Shikachuu** [comment]
Screenshot from 2022-08-11 20-49-01

**Comment by alexellis** [comment]
This will also need a rebase please.

**Comment by Shikachuu** [comment]
> This will also need a rebase please.

Done :heavy_check_mark:

**Comment by alexellis** [comment]
@vuldin how do we get your documentation updated for `arkade get rpk`?

**Comment by alexellis** [comment]
@vuldin this is ready to try: https://github.com/alexellis/arkade/releases/tag/0.8.33

Thanks to @Shikachuu

**Pull request merged**
