### PR TITLE
Add mkcert to arkade get

### PR DESCRIPTION
**Pull request by karthick-kk**
Signed-off-by: karthick-kk <kkzone@gmail.com>

Related to https://github.com/alexellis/arkade/issues/637, it adds the mkcert cli tool to arkade get
## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

After build, tried to pull the binaries for different os with `arkade get --arch --os` and arch and validated the binary compatibility with `file` command.
```
❯ file /home/kk/.arkade/bin/mkcert
/home/kk/.arkade/bin/mkcert: Mach-O 64-bit x86_64 executable
❯ file /home/kk/.arkade/bin/mkcert
/home/kk/.arkade/bin/mkcert: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=nGEPBLojugucAhELKjVw/NhyJ8ikF1L0J5YFJmllN/ZsVrzkAywJ7Deu6DSE0i/CXo0mM_cZpFPAeagHL1h, not stripped
❯ file /home/kk/.arkade/bin/mkcert
/home/kk/.arkade/bin/mkcert: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=4vvhqUAj4ba7WEDyqQhH/0r7uSNFCZhbT9O7G21j0/Onl3pUwhjqlNEZsZdjsb/cR3rFvzUfFrPM-celNjx, not stripped
❯ file /home/kk/.arkade/bin/mkcert
/home/kk/.arkade/bin/mkcert: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Hpma7eDWQyjWP9pHgiVR/I4EJAJAH6-n9zfc3ztP0/B6-DSW5gKeUZ4mzwYihR/VCZzSh07NUPDPAOEMhXz, not stripped
❯ file /home/kk/.arkade/bin/mkcert
/home/kk/.arkade/bin/mkcert: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Shikachuu — CHANGES_REQUESTED** [review]
Hey @karthick-kk,
Thanks for contributing to arkade!
Can you indicate in the `How Has This Been Tested?` that you added unit tests as well?
Also you can get the `darwin` binaries running `arkade get` with the `--arch` and `--os` flags!
(Don't worry, in my first PRs I overlooked those flags too. :smile: )

Also, there is an `arm` binary for `mkcert`, can you add that to the template and the unit tests please?

**Comment by karthick-kk** [comment]
> Hey @karthick-kk, Thanks for contributing to arkade! Can you indicate in the `How Has This Been Tested?` that you added unit tests as well? Also you can get the `darwin` binaries running `arkade get` with the `--arch` and `--os` flags! (Don't worry, in my first PRs I overlooked those flags too. 😄 )
> 
> Also, there is an `arm` binary for `mkcert`, can you add that to the template and the unit tests please?

Thanks @Shikachuu for guiding me in right direction. Tested the binary pulls with the extra args and added the required unit tests to get_test.go. 
Both arm64 and arm binary references added now.

**Comment by Shikachuu** [comment]
Glad I could help @karthick-kk!
One last thing that I forgot to mention, can you do a rebase to only include one commit please?

**Comment by karthick-kk** [comment]
> Glad I could help @karthick-kk! One last thing that I forgot to mention, can you do a rebase to only include one commit please?

Tried some rebasing and resolved merge conflicts. Not sure how to merge the previous commits into one. Should I open a new PR?

**Comment by karthick-kk** [comment]
> Glad I could help @karthick-kk! One last thing that I forgot to mention, can you do a rebase to only include one commit please?

Awesome. All set now I guess. Merged/rebased to single commit. Unit tests passed as well.

**Comment by alexellis** [comment]
> After build, tried to pull the binaries for different os with arkade get --arch --os and arch and validated the binary compatibility with file command.

Excellent, thank you for providing this

**Pull request merged**
