### PR TITLE
change kubectl download site

### PR DESCRIPTION
**Pull request by YoninL**
Change kubectl download site from https://storage.googleapis.com/kubernetes-release/release to https://dl.k8s.io

## Description

Change kubectl download site from https://storage.googleapis.com/kubernetes-release/release to https://dl.k8s.io

## Motivation and Context

- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
According to https://github.com/kubernetes/k8s.io/issues/2396, we should migrate from gs bucket to dl.k8s.io.
Also refer to how minikube is making the change, https://github.com/kubernetes/minikube/pull/15840/files

## How Has This Been Tested?

get_test.go is updated.

If updating or adding a new CLI to `arkade get`, run:

```
go build && ./hack/test-tool.sh TOOL_NAME
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Review by Jasstkn — APPROVED** [review]
LGTM.

**Comment by YoninL** [comment]
@Jasstkn Thank you, can you help to merge this PR? I don't have write permission, thanks.

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
@Jasstkn I'm assuming you've tested this and that's why you approved the PR. I'm merging it, but I haven't tested it or verified it in any way.

Hope you're OK with sending a PR to revert this if there's an issue and breakage for users?

**Comment by alexellis** [comment]
@YoninL has also provided no evidence of testing, he changed this in the UI as you can see from "patch-1"

**Comment by alexellis** [comment]
@Jasstkn I merged this and did a release, it broke the build and we have a faulty publish:

https://github.com/alexellis/arkade/actions/runs/8029701263/job/21936281148

**Comment by YoninL** [comment]
Thanks for fixing the issue, yes, was updating in the UI, sorry I missed some links.

**Pull request merged**
