### PR TITLE
Add MetalLB app for install

### LINKED ISSUE #76: [Feature Request] Add MetalLB
If running on a set of Raspberry Pis or anywhere that does not provide a loadbalancer, we have to fall back to using host ports for Kubernetes. [MetalLB](https://metallb.universe.tf/) solves this issue by providing a bare metal load balancer implementation, and it works quite nicely I would say. I currently use it on all my clusters without any issues, and it would be great to see it added to Arkade.

The issue I see though, is that they have stopped publishing helm charts and moved to only manifests/kustomize as their officially supported deployment methods. 

Please let me know if I can help in any way.

### PR DESCRIPTION
**Pull request by jsiebens**
## Description

This PR is based on PR #329 and adds support for metallb installation. It installs metallb in L2 mode and provides an argument for configurable LB IP range (default: 192.168.0.0/24)

## Motivation and Context
Fixes #76

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Installed MetalLB on KinD (based on https://kind.sigs.k8s.io/docs/user/loadbalancer/)

Create new KinD cluster:
```
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
```
Find address pool used by loadbalancers:
```
$ docker network inspect -f '{{.IPAM.Config}}' kind
[{172.20.0.0/16  172.20.0.1 map[]} {fc00:f853:ccd:e793::/64  fc00:f853:ccd:e793::1 map[]}]
```
We want our loadbalancer IP range to come from this subclass. We can configure metallb, for instance, to use 172.20.255.200 to 172.20.255.250
```
$ ./arkade install metallb-arp --address-range "172.20.255.200-172.20.255.250"
```

Install ingress-nginx, with a LoadBalancer:
```
./arkade install ingress-nginx
```
Any pending LoadBalancer services will soon get a new IP:

```
$ kubectl get services
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.96.193.143   172.20.255.200   80:30185/TCP,443:32426/TCP   7m42s
ingress-nginx-controller-admission   ClusterIP      10.96.38.194    <none>           443/TCP                      7m42s
kubernetes                           ClusterIP      10.96.0.1       <none>           443/TCP                      10m
```

Checking my MetalLB controller logs:
```
$ kubectl logs -n metallb-system controller-6b78bff7d9-jf869
...
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.391156882Z"}
{"caller":"service.go:114","event":"ipAllocated","ip":"172.20.255.200","msg":"IP address assigned by controller","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.391425073Z"}
{"caller":"main.go:88","event":"serviceUpdated","msg":"updated service object","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.409003146Z"}
{"caller":"main.go:90","event":"endUpdate","msg":"end of service update","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.409057203Z"}
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.409085505Z"}
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.409442264Z"}
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"default/ingress-nginx-controller","ts":"2021-08-30T07:04:07.409473032Z"}
...
```

## Are you a GitHub Sponsor (Yes/No?)

- [x] Yes
- [ ] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [x] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for taking this over.

I'm not a MetalLB user, but I wonder if it only works on k3s/kubeadm rather than in a container, because 172.16.0.0 doesn't look right. Shouldn't it have been 172.16.0.1?

**Comment by jsiebens** [comment]
I actually just took the description of the original PR :innocent: 
The PR is now updated with my own test results.

**Comment by alexellis** [comment]
Looks great, thank you!

**Comment by alexellis** [comment]
Merged

**Pull request merged**
