### PR TITLE
github actions pinned to go 1.13

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

## Description
Github actions pinned to go 1.13.

## Motivation and Context

Solves #269.
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Screen Shot 2020-11-09 at 16 28 46
Screen Shot 2020-11-09 at 16 36 21

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
Sorry I don't think that you've tested this PR.

Look at the errors -> https://github.com/alexellis/arkade/actions/runs/353902765

Can you test it on your own fork and when working, update the PR with details on how you tested it?

**Review by alexellis — CHANGES_REQUESTED** [review]
Invalid YAML error in the checks

**Comment by developer-guy** [comment]
> Invalid YAML error in the checks

done.

**Comment by alexellis** [comment]
LGTM

**Pull request merged**
