### PR TITLE
Upgrade issuers to cert-manager v1

### LINKED ISSUE #253: Upgrade cert-manager app to 1.0
Upgrade [cert-manager app to 1.0](https://cert-manager.io/docs/tutorials/acme/http-validation/)

## Impacted files

The installer and the two "ingress" generators that we have which use cert-manager's shim to get certificates:

```bash
https://github.com/alexellis/arkade/blob/master/cmd/apps/certmanager_app.go
```

Upgrade to the new schema as per `cert-manager.io/v1` - [example](https://cert-manager.io/docs/tutorials/acme/http-validation/)
```bash
https://github.com/alexellis/arkade/blob/master/cmd/apps/openfaas_ingress_app.go
https://github.com/alexellis/arkade/blob/master/cmd/apps/registry_ingress_app.go
```

Note that more than just the name changed.

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description
This upgrades the issuers in ingress apps to v1 cert manager API

Tested by installing and creting ingresses with arkade

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Fixes #253
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by alexellis** [comment]
More than the namespace changed. There are links to details on the issue #253 

You'll see a similar schema change made for the inlets docs here too -> https://github.com/inlets/docs/commit/39e997de746c8183eb360e12492139d13420d7ce

**Review by alexellis — CHANGES_REQUESTED** [review]
The schema has broader changes to consider.

**Comment by Waterdrips** [comment]
ok, i looked through and the only change in our configs is adding the selectors to the issuers

**Comment by alexellis** [comment]
Do they apply + work after the change?

**Comment by Waterdrips** [comment]
yes, works with new change of selector

**Comment by alexellis** [comment]
Thank you

**Pull request merged**
