### PR TITLE
Fixes #43: Add redis app

### LINKED ISSUE #43: Add app for Redis
## App

Redis, via Bitnami's chart

This is only available for amd64

https://github.com/bitnami/charts/tree/master/upstreamed/redis

### PR DESCRIPTION
**Pull request by aidun**
Fixes #43: Add redis app

- Helm3 only
- No arm support

## Description

Add the bitnami redis chart as app.

## Motivation and Context

#43 

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

non ARM:
```
arkade install redis
export REDIS_PASSWORD=$(kubectl get secret --namespace redis redis -o jsonpath="{.data.redis-password}" | base64 --decode)
kubectl run --namespace redis redis-client --rm --tty -i --restart='Never' --env REDIS_PASSWORD=$REDIS_PASSWORD --image docker.io/bitnami/redis:5.0.7-debian-10-r48 -- bash
redis-cli -a $REDIS_PASSWORD redis-master
# here you should be connected to the master
```
ARM:
```
arkade install redis
> Node architecture: "arm64"
> Error: only Intel, i.e. PC architecture is supported for this app
```

Intel: k3d on amd64 host
ARM: k3sup on raspi

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@kadern0 and/or @Waterdrips please could you review this app and give the PR a test run? Whoever can get there first.

I like to use the Hub CLI for this

```
hub pr list
hub pr checkout
```

**Comment by kadern0** [comment]
ARM works as expected:
```
 ./arkade install redis
Node architecture: "arm"
Error: only Intel, i.e. PC architecture is supported for this app
```
Geting this error on x86:
```
kaderno@kaderno-XPS-13-9360:~/go/src/github.com/alexellis/test/arkade$ ./arkade install redis
Node architecture: "amd64"
2020/03/15 09:37:32 Client: x86_64, Linux
2020/03/15 09:37:32 User dir established as: /home/kaderno/.arkade/
"bitnami-redis" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "inlets" chart repository
...Successfully got an update from the "traefik" chart repository
...Unable to get an update from the "kadern0" chart repository (https://kadern0.github.io/helm-chart/):
	failed to fetch https://kadern0.github.io/helm-chart/index.yaml : 404 Not Found
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "bitnami-redis" chart repository
...Successfully got an update from the "openfaas" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
VALUES values.yaml
Command: /home/kaderno/.arkade/bin/helm3/helm [upgrade --install redis bitnami-redis/redis --namespace redis --version 10.5.7 --values /tmp/charts/redis/values.yaml --set serviceAccount.create=true --set rbac.create=true]
Release "redis" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Role): missing required field "rules" in io.k8s.api.rbac.v1.Role
Error: exit code 1, stderr: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Role): missing required field "rules" in io.k8s.api.rbac.v1.Role
```
Maybe @Waterdrips can have a second look just in case my K8s cluster is a bit messed up.

**Comment by kadern0** [comment]
@Waterdrips does this one work for you? I can rebuild my x86 cluster and give it another go.

**Comment by alexellis** [comment]
@kadern0 could you re-test, but please wait for @aidun to rebase first.

@aidun we need a rebase on this please.

**Comment by aidun** [comment]
@kadern0 @alexellis  is rebased and ready for testing

**Comment by alexellis** [comment]
Seems like we have a CI problem?

**Comment by alexellis** [comment]
Pushed up a merge conflict maybe?

Screenshot 2020-04-08 at 11 25 33

**Comment by alexellis** [comment]
@Waterdrips are you getting the messages here?

**Comment by Waterdrips** [comment]
> @Waterdrips are you getting the messages here?

yes

**Comment by Waterdrips** [comment]
installs and pods start on k3d locally. 
Password command shown in output is correct and i was able to create a pod and connect to the MASTER and issue some basic redis commands.


can't check ARM, don't have anything setup

**Comment by kadern0** [comment]
@Waterdrips this is still not working for me. The code creates a serviceAccount and a rbac:

```
		// define the values to override
		// due the missing arm support. datasource and dashboard sidecars are not possible
		overrides := map[string]string{
			"serviceAccount.create": "true",
			"rbac.create":           "true",
		}
```
But then the chart doesn't define any rules:

```
rbac:
  ## Specifies whether RBAC resources should be created
  ##
  create: false

  role:
    ## Rules to create. It follows the role specification
    # rules:
    #  - apiGroups:
    #    - extensions
    #    resources:
    #      - podsecuritypolicies
    #    verbs:
    #      - use
    #    resourceNames:
    #      - gce.unprivileged
    rules: []
```

This is the error I'm getting:
```
Command: /home/kaderno/.arkade/bin/helm3/helm [upgrade --install redis bitnami-redis/redis --namespace redis --version 10.5.7 --values /tmp/charts/redis/values.yaml --set serviceAccount.create=true --set rbac.create=true]
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Role): missing required field "rules" in io.k8s.api.rbac.v1.Role
Error: exit code 1, stderr: Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Role): missing required field "rules" in io.k8s.api.rbac.v1.Role
```
Are those overrides necessary?  Don't you get this validation error?

**Comment by aidun** [comment]
I checkt it. There no issues on my machine. I tested it on a fresh k3d ("v1.16.3-k3s.2") cluster on docker for desktop with my Mac. Maybe you have a new or older version and the chart is not compatible?

**Comment by kadern0** [comment]
This is the version I'm running:
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Waterdrips** [comment]
> This is the version I'm running:
> 
> ```
>  kubectl version
> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
> ```

running more than 1 kubectl version ahead or behind your k8s cluster is not recommended https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

**Comment by kadern0** [comment]
I've tried it on minikube and it works fine so it's probably something with my x86 cluster.

**Comment by alexellis** [comment]
@kadern0 @Waterdrips @aidun 

What's the latest on this, should we move forward with the rebase and then merge of this PR?

**Comment by kadern0** [comment]
It seemed to be working fine so it should be good for merging after the rebase.

**Comment by aidun** [comment]
I think I have some git trouble while rebasing... please don't merge, I have to fix it.

**Comment by aidun** [comment]
Closed in favor for #125 because I messed up my git repo :/

**Pull request closed without merging**
