### PR TITLE
Add ming to clusterctl

### PR DESCRIPTION
**Pull request by joebowbeer**
## Description
Fix clusterctl install in Git-Bash on windows (ming) 

## Motivation and Context
Was installing linux version in Git-Bash

## How Has This Been Tested?
make e2e
```bash
=== RUN   Test_DownloadClusterctl
--- PASS: Test_DownloadClusterctl (0.00s)
=== RUN   Test_CheckTools/Download_of_clusterctl
=== PAUSE Test_CheckTools/Download_of_clusterctl
=== CONT  Test_CheckTools/Download_of_clusterctl
--- PASS: Test_CheckTools/Download_of_clusterctl (0.54s)
```

hack/test-tool.sh clusterctl
```bash
$ ./hack/test-tool.sh clusterctl
+ ./arkade get clusterctl --arch arm64 --os darwin --quiet
+ file /c/Users/joebo/.arkade/bin/clusterctl
/c/Users/joebo/.arkade/bin/clusterctl: Mach-O 64-bit x86_64 executable
+ rm /c/Users/joebo/.arkade/bin/clusterctl
+ echo

+ ./arkade get clusterctl --arch x86_64 --os darwin --quiet
+ file /c/Users/joebo/.arkade/bin/clusterctl
/c/Users/joebo/.arkade/bin/clusterctl: Mach-O 64-bit x86_64 executable
+ rm /c/Users/joebo/.arkade/bin/clusterctl
+ echo

+ ./arkade get clusterctl --arch x86_64 --os linux --quiet
+ file /c/Users/joebo/.arkade/bin/clusterctl
/c/Users/joebo/.arkade/bin/clusterctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=SwmPuQyWZlCdmV-ceMW0/wTJSSLSTDQTIzgowaY5B/CSMXjlIkxgBKVqh6LH7H/S2d9aZQGYqU2s8_sf1HV, with debug_info, not stripped
+ rm /c/Users/joebo/.arkade/bin/clusterctl
+ echo

+ ./arkade get clusterctl --arch aarch64 --os linux --quiet
+ file /c/Users/joebo/.arkade/bin/clusterctl
/c/Users/joebo/.arkade/bin/clusterctl: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=gxnSABbwln8hVnfrn8UD/mBzQvPWsNjED0RhOSfmS/T4Z-6-Tu1pmxT4jAwXSn/2nbNptuSFdymad9qmjUX, with debug_info, not stripped
+ rm /c/Users/joebo/.arkade/bin/clusterctl
+ echo

+ ./arkade get clusterctl --arch x86_64 --os mingw --quiet
+ file /c/Users/joebo/.arkade/bin/clusterctl.exe
/c/Users/joebo/.arkade/bin/clusterctl.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /c/Users/joebo/.arkade/bin/clusterctl.exe
+ echo
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by joebowbeer** [comment]
@alexellis 

The e2e test failure appears to be unrelated:

`--- FAIL: Test_CheckTools/Download_of_jq (0.06s)`

**Comment by alexellis** [comment]
Thanks for sending this PR @joebowbeer 

jq seems to have relocated their code as per #918 

Would you mind updating the URLs within this PR and we'll get two fixes in one that way?

Alex

**Comment by Obsecurus** [comment]
> Thanks for sending this PR @joebowbeer
> 
> jq seems to have relocated their code as per #918
> 
> Would you mind updating the URLs within this PR and we'll get two fixes in one that way?
> 
> Alex

I cut this fix in https://github.com/alexellis/arkade/pull/919 given it seems to be hitting a few different people.

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
