### PR TITLE
feat: add Bun to System apps

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

## Description

Adding Bun to System Apps as alternative to Node.js

## Motivation and Context

- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```bash
docker container run --rm -v $(pwd):/workspace -ti golang:1.17 bash
root@371d64b6de21:/go# cd /workspace/
root@371d64b6de21:/workspace# go mod tidy && go run .
go: downloading github.com/spf13/cobra v1.5.0
go: downloading github.com/alexellis/go-execute v0.5.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/cheggaaa/pb/v3 v3.1.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/otiai10/copy v1.7.0
go: downloading github.com/sethvargo/go-password v0.2.0
go: downloading golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d
go: downloading golang.org/x/mod v0.5.1
go: downloading github.com/VividCortex/ewma v1.2.0
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading golang.org/x/sys v0.0.0-20220627191245-f75cf1eec38b
go: downloading github.com/otiai10/mint v1.3.3
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Usage:
  arkade [flags]
  arkade [command]

Available Commands:
  completion  Output shell completion for the given shell (bash or zsh)
  get         The get command downloads a tool
  help        Help about any command
  info        Find info about a Kubernetes app
  install     Install Kubernetes apps from helm charts or YAML files
  kasten      Sponsored Apps for kasten
  system      System apps
  uninstall   Uninstall apps installed with arkade
  update      Print update instructions
  venafi      Sponsored Apps for Venafi
  version     Print the version

Flags:
  -h, --help   help for arkade

Use "arkade [command] --help" for more information about a command.
root@371d64b6de21:/workspace# ./arkade system install bun
Installing Bun to /usr/local/bin
Installing version: bun-v0.1.8 for: x64
Downloading from: https://github.com/oven-sh/bun/releases/download/bun-v0.1.8/bun-linux-x64.zip
31.66 MiB / 31.66 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00%
Downloaded to: /tmp/bun-linux-x64.zip
Unpacking binaries to: /tmp/bun3489873688
Copying binaries to: /usr/local/bin
root@371d64b6de21:/workspace# bun
bun: a fast bundler, transpiler, JavaScript Runtime and package manager for web software.

  dev       ./a.ts ./b.jsx        Start a bun Dev Server
  bun       ./a.ts ./b.jsx        Bundle dependencies of input files into a .bun

  init                            Start an empty Bun project from a blank template
  create    next ./app            Create a new project from a template (bun c)
  run       test                  Run JavaScript with bun, a package.json script, or a bin
  install                         Install dependencies for a package.json (bun i)
  add       @compiled/react       Add a dependency to package.json (bun a)
  link                            Link an npm package globally
  remove    webpack               Remove a dependency from package.json (bun rm)
  unlink                          Globally unlink an npm package

  upgrade                         Get the latest version of bun
  completions                     Install shell completions for tab-completion
  discord                         Open bun's Discord server
  help                            Print this help menu
```

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [x] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

**Comment by dirien** [comment]
Bun is 🔥 and, if it goes like this soon the alternative to node. I would have it as an alternative to node on system apps level.

**Comment by alexellis** [comment]
Can you try it out as a regular CLI app lease?

I want the system apps to be kept to an absolute minimum due to their maintenance overheads.

**Comment by Shikachuu** [comment]
> Can you try it out as a regular CLI app lease?
> 
> I want the system apps to be kept to an absolute minimum due to their maintenance overheads.

I also back this!
It is waaay easier to maintain and refactor regular CLI tools when breaking changes come to the target tool, which is likely to happen with `bun` since it isn't hit 1.0.0 yet.

**Comment by dirien** [comment]
HI @alexellis,

np -> https://github.com/alexellis/arkade/pull/735

**Pull request closed without merging**
